### ISSUE TITLE
Error with textDocument/hover

### ISSUE THREAD

**Issue by mischnic** [palantir/python-language-server#136]
I am using this with SublimeText (https://github.com/tomv564/LSP), I hope this is the correct place for posting.

The error occurs when hovering over a symbol.

```
LSP: request 13: textDocument/hover 
LSP: (stderr):  b'2017-09-13 21:44:08,255 UTC - ERROR - pyls.language_server - CAUGHT'
LSP: (stderr):  b'Traceback (most recent call last):'
LSP: (stderr):  b'File "/Library/Python/2.7/site-packages/pyls/language_server.py", line 66, in wrapped'
LSP: (stderr):  b'return func(*args, **kwargs)'
LSP: (stderr):  b'File "/Library/Python/2.7/site-packages/pyls/python_ls.py", line 129, in m_text_document__hover'
LSP: (stderr):  b"return self.hover(textDocument['uri'], position)"
LSP: (stderr):  b'File "/Library/Python/2.7/site-packages/pyls/python_ls.py", line 81, in hover'
LSP: (stderr):  b"return self._hook('pyls_hover', doc_uri, position=position) or {'contents': ''}"
LSP: (stderr):  b'File "/Library/Python/2.7/site-packages/pyls/python_ls.py", line 18, in _hook'
LSP: (stderr):  b'doc = self.workspace.get_document(doc_uri) if doc_uri else None'
LSP: (stderr):  b'File "/Library/Python/2.7/site-packages/pyls/workspace.py", line 48, in get_document'
LSP: (stderr):  b'return self._docs[doc_uri]'
LSP: (stderr):  b"KeyError: u'file:///Users/..../file.py'"

LSP: (stderr):  b'2017-09-13 21:44:08,256 UTC - ERROR - jsonrpc.manager - API Exception: {\'message\': "u\'file:///Users/..../file.py\'", \'args\': (u\'file:///Users/..../file.py\',), \'type\': \'KeyError\'}'
LSP: (stderr):  b'Traceback (most recent call last):'
LSP: got json:  LSP: (stderr): {"jsonrpc":"2.0","id":13,"error":{"message":"Server error","code":-32000,"data":{"message":"u'file:///Users/..../file.py'","args":["file:///Users/niklas/Documents/
LSP: got error:  {'data': {'type': 'KeyError', 'args': ['file:///Users/..../file.py'], 'message': "u'file:///Users/..../file.py'"}, 'code': -32000, 'message': 'Server error'}
 b'File "/Library/Python/2.7/site-packages/jsonrpc/manager.py", line 108, in _get_responses'
LSP: (stderr):  b'result = method(*request.args, **request.kwargs)'
LSP: (stderr):  b'File "/Library/Python/2.7/site-packages/pyls/language_server.py", line 66, in wrapped'
LSP: (stderr):  b'return func(*args, **kwargs)'
LSP: (stderr):  b'File "/Library/Python/2.7/site-packages/pyls/python_ls.py", line 129, in m_text_document__hover'
LSP: (stderr):  b"return self.hover(textDocument['uri'], position)"
LSP: (stderr):  b'File "/Library/Python/2.7/site-packages/pyls/python_ls.py", line 81, in hover'
LSP: (stderr):  b"return self._hook('pyls_hover', doc_uri, position=position) or {'contents': ''}"
LSP: (stderr):  b'File "/Library/Python/2.7/site-packages/pyls/python_ls.py", line 18, in _hook'
LSP: (stderr):  b'doc = self.workspace.get_document(doc_uri) if doc_uri else None'
LSP: (stderr):  b'File "/Library/Python/2.7/site-packages/pyls/workspace.py", line 48, in get_document'
LSP: (stderr):  b'return self._docs[doc_uri]'
LSP: (stderr):  b"KeyError: u'file:///Users/..../file.py'"
```

**Comment by tomv564** [comment]
Hi @mischnic, python language service logs that it does not know about your 'file.py', it expects to see a `textdocument/didOpen file.py` notification from LSP before any hover requests are sent.

Although python-language-service could technically support this, we probably should look at LSP first.
* Can you confirm if LSP sent a `didOpen` for the file?
* What is the `rootUri` used in LSP's `initialize` call?

**Comment by mischnic** [comment]
While trying to get the `rootUri` I restarted SublimeText. After that, everything seems to work fine. 

Below is what I could found, if the error occurs again I will try to find out the `rootUri`.

---

> `sublime.active_window().active_view().settings().get("syntax")`

Prints out `'Packages/Python/Python.sublime-syntax'`.

> What is the `rootUri` used in LSP's `initialize` call?

-

> Can you confirm if LSP sent a `didOpen` for the file?

Here's the log: ('python-ci.py' is 'file.py')

```
LSP: Config added: dotty
LSP: Config added: jsts
LSP: Config added: rls
LSP: Config added: pyls
LSP: Config added: clangd
LSP: no clients found for window 2
LSP: no clients found for window 2
LSP: starting in /Users/niklas/Documents/python-ci
LSP: starting ['pyls']
LSP: request 1: initialize 
LSP: client registered for window 2 {'pyls': <LSP.main.Client object at 0x10d34e990>}
LSP: got json:  {"jsonrpc":"2.0","result":{"capabilities":{"executeCommandProvider":{"commands":[]},"hoverProvider":true,"referencesProvider":true,"textDocumentSync":2,"documentFormattingProvider":true,"signatureHelp
LSP: notify: textDocument/didOpen
LSP: got json:  {"jsonrpc":"2.0","params":{"uri":"file:///Users/niklas/Documents/python-ci/python-ci.py","diagnostics":[]},"method":"textDocument/publishDiagnostics"}
```

**Comment by tomv564** [comment]
Great, thanks for troubleshooting. If you can repro when LSP neglects to send a `didOpen` before interacting with a document, please submit an issue to LSP (with the logs).

**Comment by gatesn** [comment]
Going to close this out, as it seems like it could be a client issue.
