### ISSUE TITLE
pyls 1.11.1 crashes while handling completion request

### ISSUE THREAD

**Issue by deathaxe** [palantir/python-language-server#183]
Here's a detailed debug log of a crash situation in the latest release.

I just typed `self.` within a class method.

```python
class ClassName(obj):

    def member(self):
        self.    # crash
```

Log:

```
2017-11-03 18:14:14,119 UTC - DEBUG - pyls.server - Got message: b'{"jsonrpc": "2.0", "id": 4, "method": "textDocument/completion", "params": {"textDocument": {"uri": "file:///C:/Apps/Sublime/Data/Packages/GitGutter/modules/handler.py"}, "position": {"line": 331, "character": 13}}}'
2017-11-03 18:14:14,119 UTC - DEBUG - pyls._utils - Racing hook impls for hook <_HookCaller 'pyls_completions'>: [<pluggy.HookImpl object at 0x0000014CE1EA1668>, <pluggy.HookImpl object at 0x0000014CE1ED5898>]
2017-11-03 18:14:14,119 UTC - DEBUG - pyls.plugins.jedi_completion - Launching Jedi
2017-11-03 18:14:14,119 UTC - DEBUG - pyls.plugins.rope_completion - Launching Rope
2017-11-03 18:14:14,119 UTC - DEBUG - root - diff parser start
2017-11-03 18:14:14,119 UTC - DEBUG - root - diff parser calculated
2017-11-03 18:14:14,119 UTC - DEBUG - root - diff: line_lengths old: 830, new: 830
2017-11-03 18:14:14,135 UTC - DEBUG - root - diff equal old[1:331] new[1:331]
2017-11-03 18:14:14,135 UTC - DEBUG - root - diff actually copy 1 to 331
2017-11-03 18:14:14,135 UTC - DEBUG - root - diff replace old[332:332] new[332:332]
2017-11-03 18:14:14,135 UTC - DEBUG - root - parse_part from 332 to 332 (to 332 in part parser)
2017-11-03 18:14:14,135 UTC - DEBUG - root - diff equal old[333:830] new[333:830]
2017-11-03 18:14:14,135 UTC - DEBUG - root - diff actually copy 333 to 342
2017-11-03 18:14:14,150 UTC - DEBUG - root - diff actually copy 343 to 829
2017-11-03 18:14:14,150 UTC - DEBUG - root - diff parser end
2017-11-03 18:14:14,525 UTC - DEBUG - root - diff parser start
2017-11-03 18:14:14,525 UTC - DEBUG - root - diff parser calculated
2017-11-03 18:14:14,525 UTC - DEBUG - root - diff: line_lengths old: 830, new: 829
2017-11-03 18:14:14,525 UTC - DEBUG - root - diff equal old[1:331] new[1:331]
2017-11-03 18:14:14,525 UTC - DEBUG - root - diff actually copy 1 to 331
2017-11-03 18:14:14,525 UTC - DEBUG - root - diff delete old[332:332] new[332:331]
2017-11-03 18:14:14,525 UTC - DEBUG - root - diff equal old[333:830] new[332:829]
2017-11-03 18:14:14,525 UTC - DEBUG - root - diff actually copy 332 to 341
2017-11-03 18:14:14,525 UTC - DEBUG - root - diff actually copy 341 to 828
2017-11-03 18:14:14,525 UTC - DEBUG - root - diff parser end
2017-11-03 18:14:14,635 UTC - DEBUG - pyls.config -   pyls_lint [hook]
      config: <pyls.config.Config object at 0x0000014CE1EB2128>
      workspace: <pyls.workspace.Workspace object at 0x0000014CE1EA1EB8>
      document: file:///C:/Apps/Sublime/Data/Packages/GitGutter/modules/handler.py

2017-11-03 18:14:14,635 UTC - DEBUG - pyls.config - Loaded configuration from []
2017-11-03 18:14:14,635 UTC - DEBUG - pyls.config - Loaded configuration from []
2017-11-03 18:14:14,666 UTC - DEBUG - pyls.config - Loaded configuration from ['c:\\Apps\\Sublime\\Data\\Packages\\GitGutter\\setup.cfg']
2017-11-03 18:14:14,666 UTC - DEBUG - pyls.config - Loaded configuration from ['c:\\Apps\\Sublime\\Data\\Packages\\GitGutter\\setup.cfg']
2017-11-03 18:14:14,666 UTC - DEBUG - pyls.plugins.pycodestyle_lint - Got pycodestyle config: {'verbose': 0, 'quiet': 0, 'repeat': True, 'exclude': '.svn,CVS,.bzr,.hg,.git,__pycache__,.tox', 'filename': '*.py', 'select': '', 'ignore': 'E722', 'show_source': None, 'show_pep8': None, 'statistics': None, 'count': None, 'max_line_length': 80, 'hang_closing': None, 'format': 'default', 'diff': None, 'benchmark': None}
2017-11-03 18:14:14,744 UTC - DEBUG - pyls.config -   finish pyls_lint --> [[{'source': 'pyflakes', 'range': {'start': {'line': 331, 'character': 14}, 'end': {'line': 331, 'character': 28}}, 'message': 'invalid syntax', 'severity': 1}], []] [hook]

2017-11-03 18:14:14,760 UTC - DEBUG - pyls.server - Sending notification textDocument/publishDiagnostics: {'uri': 'file:///C:/Apps/Sublime/Data/Packages/GitGutter/modules/handler.py', 'diagnostics': [{'source': 'pyflakes', 'range': {'start': {'line': 331, 'character': 14}, 'end': {'line': 331, 'character': 28}}, 'message': 'invalid syntax', 'severity': 1}]}
2017-11-03 18:14:14,822 UTC - ERROR - pyls.language_server - CAUGHT
Traceback (most recent call last):
  File "c:\apps\python36\lib\site-packages\jedi\cache.py", line 116, in wrapper
    return dct[key]
KeyError: ((), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\apps\python36\lib\site-packages\pyls\language_server.py", line 66, in wrapped
    return func(*args, **kwargs)
  File "c:\apps\python36\lib\site-packages\pyls\python_ls.py", line 138, in m_text_document__completion
    return self.completions(textDocument['uri'], position)
  File "c:\apps\python36\lib\site-packages\pyls\python_ls.py", line 68, in completions
    position=position
  File "c:\apps\python36\lib\site-packages\pyls\_utils.py", line 52, in race_hooks
    for impl, result in pool.imap_unordered(_apply, impls, chunksize=1):
  File "c:\apps\python36\lib\multiprocessing\pool.py", line 748, in next
    raise value
  File "c:\apps\python36\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "c:\apps\python36\lib\site-packages\pyls\_utils.py", line 47, in _apply
    return impl, impl.function(**kwargs)
  File "c:\apps\python36\lib\site-packages\pyls\plugins\jedi_completion.py", line 20, in pyls_completions
    } for d in definitions]
  File "c:\apps\python36\lib\site-packages\pyls\plugins\jedi_completion.py", line 20, in <listcomp>
    } for d in definitions]
  File "c:\apps\python36\lib\site-packages\pyls\plugins\jedi_completion.py", line 27, in _label
    params = ", ".join(param.name for param in definition.params)
  File "c:\apps\python36\lib\site-packages\jedi\cache.py", line 118, in wrapper
    result = method(self, *args, **kwargs)
  File "c:\apps\python36\lib\site-packages\jedi\api\classes.py", line 347, in params
    raise AttributeError()
AttributeError
2017-11-03 18:14:14,838 UTC - ERROR - jsonrpc.manager - API Exception: {'type': 'AttributeError', 'args': (), 'message': ''}
Traceback (most recent call last):
  File "c:\apps\python36\lib\site-packages\jedi\cache.py", line 116, in wrapper
    return dct[key]
KeyError: ((), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\apps\python36\lib\site-packages\jsonrpc\manager.py", line 112, in _get_responses
    result = method(*request.args, **request.kwargs)
  File "c:\apps\python36\lib\site-packages\pyls\language_server.py", line 66, in wrapped
    return func(*args, **kwargs)
  File "c:\apps\python36\lib\site-packages\pyls\python_ls.py", line 138, in m_text_document__completion
    return self.completions(textDocument['uri'], position)
  File "c:\apps\python36\lib\site-packages\pyls\python_ls.py", line 68, in completions
    position=position
  File "c:\apps\python36\lib\site-packages\pyls\_utils.py", line 52, in race_hooks
    for impl, result in pool.imap_unordered(_apply, impls, chunksize=1):
  File "c:\apps\python36\lib\multiprocessing\pool.py", line 748, in next
    raise value
  File "c:\apps\python36\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "c:\apps\python36\lib\site-packages\pyls\_utils.py", line 47, in _apply
    return impl, impl.function(**kwargs)
  File "c:\apps\python36\lib\site-packages\pyls\plugins\jedi_completion.py", line 20, in pyls_completions
    } for d in definitions]
  File "c:\apps\python36\lib\site-packages\pyls\plugins\jedi_completion.py", line 20, in <listcomp>
    } for d in definitions]
  File "c:\apps\python36\lib\site-packages\pyls\plugins\jedi_completion.py", line 27, in _label
    params = ", ".join(param.name for param in definition.params)
  File "c:\apps\python36\lib\site-packages\jedi\cache.py", line 118, in wrapper
    result = method(self, *args, **kwargs)
  File "c:\apps\python36\lib\site-packages\jedi\api\classes.py", line 347, in params
    raise AttributeError()
AttributeError
2017-11-03 18:14:14,854 UTC - DEBUG - pyls.plugins.rope_completion - Rope finished
```

**Comment by gatesn** [comment]
I'm unable to reproduce this right now. Let's re-open if it crops up again.
