### ISSUE TITLE
Server dying because of EOFError

### ISSUE THREAD

**Issue by languitar** [palantir/python-language-server#203]
When using this language server with https://github.com/autozimu/LanguageClient-neovim I am frequently seeing crashes of the following form:

```
2017-12-13 11:12:01,258 UTC - ERROR - pyls.server - Language server exiting due to uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pyls/server.py", line 34, in handle
    data = self._read_message()
  File "/usr/lib/python3.6/site-packages/pyls/server.py", line 91, in _read_message
    raise EOFError(
```

I am running version 0.11.1 of the server.

**Comment by gatesn** [comment]
EOF here is raised when stdin is closed. Looks like the client crashes, closing stdin, that causes the server to crash.

**Comment by gatesn** [comment]
Closing since this is a client problem
