### ISSUE TITLE
ParseError: Cannot parse file

### ISSUE THREAD

**Issue by SamVerschueren** [palantir/python-language-server#205]
Hi

I'm using the language server in combination with the monaco editor. It works fine, but sometimes I get the following error.

```
Python Server: Exception in thread Thread-161:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 1082, in run
    self.function(*self.args, **self.kwargs)
  File "/Users/sam/Library/Python/2.7/lib/python/site-packages/python_language_server-0.12.0-py2.7.egg/pyls/python_ls.py", line 100, in lint
    self.workspace.publish_diagnostics(doc_uri, flatten(self._hook('pyls_lint', doc_uri)))
  File "/Users/sam/Library/Python/2.7/lib/python/site-packages/python_language_server-0.12.0-py2.7.egg/pyls/python_ls.py", line 28, in _hook
    return self._hook_caller(hook_name)(config=self.config, workspace=self.workspace, document=doc, **kwargs)
  File "/Users/sam/Library/Python/2.7/lib/python/site-packages/pluggy/__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/Users/sam/Library/Python/2.7/lib/python/site-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/sam/Library/Python/2.7/lib/python/site-packages/pluggy/__init__.py", line 182, in __call__
    return outcome.get_result()
  File "/Users/sam/Library/Python/2.7/lib/python/site-packages/pluggy/callers.py", line 77, in get_result
    _reraise(*ex)  # noqa
  File "/Users/sam/Library/Python/2.7/lib/python/site-packages/pluggy/callers.py", line 48, in from_call
    result = func()
  File "/Users/sam/Library/Python/2.7/lib/python/site-packages/pluggy/__init__.py", line 180, in <lambda>
    outcome = _Result.from_call(lambda: self.oldcall(hook, hook_impls, kwargs))
  File "/Users/sam/Library/Python/2.7/lib/python/site-packages/pluggy/__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/Users/sam/Library/Python/2.7/lib/python/site-packages/pluggy/callers.py", line 201, in _multicall
    return outcome.get_result()
  File "/Users/sam/Library/Python/2.7/lib/python/site-packages/pluggy/callers.py", line 77, in get_result
    _reraise(*ex)  # noqa
  File "/Users/sam/Library/Python/2.7/lib/python/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/Users/sam/Library/Python/2.7/lib/python/site-packages/python_language_server-0.12.0-py2.7.egg/pyls/plugins/pydocstyle_lint.py", line 32, in pyls_lint
    for err in errors:
  File "/Users/sam/Library/Python/2.7/lib/python/site-packages/pydocstyle/checker.py", line 64, in check_source
    module = parse(StringIO(source), filename)
  File "/Users/sam/Library/Python/2.7/lib/python/site-packages/pydocstyle/parser.py", line 305, in __call__
    return self.parse(*args, **kwargs)
  File "/Users/sam/Library/Python/2.7/lib/python/site-packages/pydocstyle/parser.py", line 294, in parse
    six.raise_from(ParseError(), error)
  File "/Users/sam/Library/Python/2.7/lib/python/site-packages/six.py", line 737, in raise_from
    raise value
ParseError: Cannot parse file.
```

Any idea what causes this error? It looks like something in the `pydocstyle` parser. To be honest, I want to disable that plugin as I'm currently only interested in auto completion but I'm not entirely sure on how to disable that plugin without compiling the language server myself.

**Comment by gatesn** [comment]
Hi @SamVerschueren, could you paste the contents of the file(s) you had open at the time this error was thrown? 

To disable the plugin, you can set the `pyls.plugins.pydocstyle.enabled` property to `False`. How you do this depends on the client you're using.

**Comment by SamVerschueren** [comment]
I have a file `test.py` and this is what I want to type

```
from keras.models import Sequential
```

The moment I type `from`, the error pops up.


![kapture 2017-12-21 at 19 31 47](https://user-images.githubusercontent.com/1913805/34269686-a440963e-e685-11e7-9666-42d2f1578c58.gif)

-----------------------
I use [monaco-languageclient](https://github.com/TypeFox/monaco-languageclient) with the [monaco-editor](https://github.com/Microsoft/monaco-editor).  Still have to find out how to override those settings.

**Comment by SamVerschueren** [comment]
I'm able to override configure the language service, so that's covered :).

**Comment by gatesn** [comment]
Do you pass a workspaceRoot when initialising?

**Comment by SamVerschueren** [comment]
No, didn't know that was necessary. Thanks for the tip, I'll try it out.

**Comment by gatesn** [comment]
It's not necessary for the LSP, but I'm not sure Pyls handles the case particularly well right now...

**Comment by SamVerschueren** [comment]
Thanks for fixing this! :)
