### ISSUE TITLE
TypeError: Object of type 'getset_descriptor' is not JSON serializable

### ISSUE THREAD

**Issue by languitar** [palantir/python-language-server#244]
It seems version 0.12.2 died from a file with broken syntax:

```
2018-01-25 19:44:44,430 UTC - ERROR - pyls.server - Language server exiting due to uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pyls/server.py", line 51, in handle
    self._write_message(response.data)
  File "/usr/lib/python3.6/site-packages/pyls/server.py", line 106, in _write_message
    body = json.dumps(msg, separators=(",", ":"))
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'getset_descriptor' is not JSON serializable
```

The full log of the session can be found here: https://gist.github.com/922e282860437ba54e19e2e2c01d2eee

**Comment by gatesn** [comment]
Looks like the issue here is that we inline some data types in our JSON RPC messages, yet not all types are serialisable.

**Comment by gatesn** [comment]
A lot of code has changed since 0.12.2, so closing this out. Please re-open if the issue persists.
