### ISSUE TITLE
KeyError in workspace.py line 110, in get_document

### ISSUE THREAD

**Issue by mcepl** [palantir/python-language-server#263]
I found this in my log:
```
2018-02-19 18:36:59,921 UTC - DEBUG - pyls.server - Got message: b'{"jsonrpc":"2.0","method":"textDocument/didClose","params":{"textDocument":{"uri":"file:///home/matej/archiv/knihovna/repos/freeipa/ipaserver/install/bindinstance.py"}}}'
2018-02-19 18:37:51,329 UTC - DEBUG - pyls.server - Got message: b'{"jsonrpc":"2.0","method":"textDocument/definition","params":{"position":{"character":10,"line":358},"textDocument":{"uri":"file:///home/matej/archiv/knihovna/repos/freeipa/ipaserver/install/bindinstance.py"}},"id":19}'
2018-02-19 18:37:51,329 UTC - ERROR - jsonrpc.manager - API Exception: {'type': 'KeyError', 'args': ('file:///home/matej/archiv/knihovna/repos/freeipa/ipaserver/install/bindinstance.py',), 'message': "'file:///home/matej/archiv/knihovna/repos/freeipa/ipaserver/install/bindinstance.py'"}
Traceback (most recent call last):
  File "/home/matej/.local/lib/python3.4/site-packages/jsonrpc/manager.py", line 112, in _get_responses
    result = method(*request.args, **request.kwargs)
  File "/home/matej/.local/lib/python3.4/site-packages/pyls/dispatcher.py", line 19, in wrapped
    return func(*args, **kwargs)
  File "/home/matej/.local/lib/python3.4/site-packages/pyls/python_ls.py", line 157, in m_text_document__definition
    return self.definitions(textDocument['uri'], position)
  File "/home/matej/.local/lib/python3.4/site-packages/pyls/python_ls.py", line 92, in definitions
    return flatten(self._hook('pyls_definitions', doc_uri, position=position))
  File "/home/matej/.local/lib/python3.4/site-packages/pyls/python_ls.py", line 39, in _hook
    doc = self.workspace.get_document(doc_uri) if doc_uri else None
  File "/home/matej/.local/lib/python3.4/site-packages/pyls/workspace.py", line 110, in get_document
    return self._docs[doc_uri]
KeyError: 'file:///home/matej/archiv/knihovna/repos/freeipa/ipaserver/install/bindinstance.py'
```
``bindinstance.py`` is [from FreeIPA](https://pagure.io/freeipa/blob/master/f/ipaserver/install/bindinstance.py) and this is [the local copy](https://github.com/palantir/python-language-server/files/1737734/bindinstance.py.txt).

**Comment by gatesn** [comment]
@mcepl this is a client bug, which language server client are you using?

**Comment by mcepl** [comment]
https://github.com/autozimu/LanguageClient-neovim with vim8 8.0.1520.

**Comment by gatesn** [comment]
@autozimu looks like the client sent didClose, and then a definition message afterwards for the same document.

**Comment by autozimu** [comment]
@mcepl please file bug in client repo following issue template.

**Comment by mcepl** [comment]
@autozimu Unfortunately, I am not able to reliably reproduce this. Are you still interested?
