### ISSUE TITLE
couldn't install

### ISSUE THREAD

**Issue by sulydee** [palantir/python-language-server#283]
When I `pip install python-language-server` to install the software and then I get back this big error message：
```
Installing collected packages: configparser, future, parso, jedi, json-rpc, mccabe, pycodestyle, snowballstemmer, six, pydocstyle, pyflakes, rope, yapf, pluggy, python-language-server
  Running setup.py install for configparser ... error
Exception:
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 20: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\program files\python36\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\program files\python36\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\program files\python36\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\program files\python36\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\program files\python36\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 20: invalid start byte
```

**Comment by ferozco** [comment]
what version of pip are you using?

**Comment by gatesn** [comment]
Closing this out since I can't repro and it seems unrelated to pyls
