### ISSUE TITLE
Block indentation followed by comment is causing crash in ast.parse()

### ISSUE THREAD

**Issue by patilarpith** [palantir/python-language-server#284]
Pyls Version: 0.14.0

Code:
```python
#!/bin/python

import sys
imp

if __name__ == "__main__":
    # Complete this


```
Line No 4 & Column No 3

Log:
```

2018-03-09 10:41:53,440 UTC - ERROR - jsonrpc.manager - API Exception: {'args': ('Syntax error in file </dev/a17cf885-0064-4fbb-b539-6750f9a9a0b9.py> line <13>: Failed to fix error: /dev/a17cf885-0064-4fbb-b539-6750f9a9a0b9.py:13 expected an indented block',), 'message': 'Syntax error in file </dev/a17cf885-0064-4fbb-b539-6750f9a9a0b9.py> line <13>: Failed to fix error: /dev/a17cf885-0064-4fbb-b539-6750f9a9a0b9.py:13 expected an indented block', 'type': 'ModuleSyntaxError'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rope/base/pyobjectsdef.py", line 189, in _init_source
    ast_node = ast.parse(source_bytes, filename=filename)
  File "/usr/local/lib/python3.5/dist-packages/rope/base/ast.py", line 21, in parse
    return compile(source, filename, 'exec', _ast.PyCF_ONLY_AST)
  File "/dev/a17cf885-0064-4fbb-b539-6750f9a9a0b9.py", line 13
    pass
       ^
IndentationError: expected an indented block

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rope/contrib/fixsyntax.py", line 32, in get_pymodule
    force_errors=True)
  File "/usr/local/lib/python3.5/dist-packages/rope/base/libutils.py", line 94, in get_string_module
    force_errors=force_errors)
  File "/usr/local/lib/python3.5/dist-packages/rope/base/pyobjectsdef.py", line 162, in __init__
    source, node = self._init_source(pycore, source, resource)
  File "/usr/local/lib/python3.5/dist-packages/rope/base/pyobjectsdef.py", line 191, in _init_source
    raise exceptions.ModuleSyntaxError(filename, e.lineno, e.msg)
rope.base.exceptions.ModuleSyntaxError: Syntax error in file </dev/a17cf885-0064-4fbb-b539-6750f9a9a0b9.py> line <13>: expected an indented block

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/jsonrpc/manager.py", line 112, in _get_responses
    result = method(*request.args, **request.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyls/dispatcher.py", line 19, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyls/python_ls.py", line 154, in m_text_document__completion
    return self.completions(textDocument['uri'], position)
  File "/usr/local/lib/python3.5/dist-packages/pyls/python_ls.py", line 85, in completions
    completions = self._hook('pyls_completions', doc_uri, position=position)
  File "/usr/local/lib/python3.5/dist-packages/pyls/python_ls.py", line 41, in _hook
    return hook(config=self.config, workspace=self.workspace, document=doc, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pluggy/__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pluggy/__init__.py", line 182, in __call__
    return outcome.get_result()
  File "/usr/local/lib/python3.5/dist-packages/pluggy/callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.5/dist-packages/pluggy/callers.py", line 48, in from_call
    result = func()
  File "/usr/local/lib/python3.5/dist-packages/pluggy/__init__.py", line 180, in <lambda>
    outcome = _Result.from_call(lambda: self.oldcall(hook, hook_impls, kwargs))
  File "/usr/local/lib/python3.5/dist-packages/pluggy/__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/usr/local/lib/python3.5/dist-packages/pluggy/callers.py", line 201, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.5/dist-packages/pluggy/callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.5/dist-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.5/dist-packages/pyls/plugins/rope_completion.py", line 31, in pyls_completions
    offset, document._rope, maxfixes=3)
  File "/usr/local/lib/python3.5/dist-packages/rope/contrib/codeassist.py", line 40, in code_assist
    return assist()
  File "/usr/local/lib/python3.5/dist-packages/rope/contrib/codeassist.py", line 382, in __call__
    completions = list(self._code_completions().values())
  File "/usr/local/lib/python3.5/dist-packages/rope/contrib/codeassist.py", line 451, in _code_completions
    pymodule = fixer.get_pymodule()
  File "/usr/local/lib/python3.5/dist-packages/rope/base/utils/__init__.py", line 12, in _wrapper
    setattr(self, name, func(self, *args, **kwds))
  File "/usr/local/lib/python3.5/dist-packages/rope/contrib/fixsyntax.py", line 43, in get_pymodule
    'Failed to fix error: {0}'.format(msg))
rope.base.exceptions.ModuleSyntaxError: Syntax error in file </dev/a17cf885-0064-4fbb-b539-6750f9a9a0b9.py> line <13>: Failed to fix error: /dev/a17cf885-0064-4fbb-b539-6750f9a9a0b9.py:13 expected an indented block
```

**Comment by ferozco** [comment]
The exception being thrown is valid, but its handling by pyls is not. Luckily in 0.15.0+ we handle all exceptions and propagate an error to the client instead of crashing

**Comment by patilarpith** [comment]
@ferozco Oh wonderful! Any plan to make a new release soon? I'm unable to switch to 0.15.0+ due to #274

**Comment by ferozco** [comment]
have you had the chance to upgrade? can i close out this issue?

**Comment by patilarpith** [comment]
@ferozco Sadly no because of #294
