### ISSUE TITLE
ImportError: cannot import name parse

### ISSUE THREAD

**Issue by henres** [palantir/python-language-server#341]
Hello, have a problem with pyls installation.
On Solus 3.
Python-language-server version 0.18.0
python 2.7

Try to use it for atom.

```bash
Traceback (most recent call last):
  File "/usr/bin/pyls", line 11, in <module>
    load_entry_point('python-language-server==0.18.0', 'console_scripts', 'pyls')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/pyls/__main__.py", line 7, in <module>
    from .python_ls import start_io_lang_server, start_tcp_lang_server, PythonLanguageServer
  File "/usr/lib/python2.7/site-packages/pyls/python_ls.py", line 5, in <module>
    from . import lsp, _utils, uris
  File "/usr/lib/python2.7/site-packages/pyls/uris.py", line 7, in <module>
    from urllib import parse
ImportError: cannot import name parse
```

**Comment by gatesn** [comment]
@henres can you show the output of `pip list` ?

**Comment by henres** [comment]
Hello sorry, i didn't see the notifications for you answer @gatesn.
Thanks for your answer:
Here the pip list :

```
 pip list
Package                      Version            
---------------------------- -------------------
apparmor                     2.11.0             
appdirs                      1.4.3              
asn1crypto                   0.23.0             
autopep8                     1.3.5              
backports.ssl-match-hostname 3.5.0.1            
beautifulsoup4               4.6.0              
cached-property              1.3.0              
catbox                       1.7.0              
certifi                      2018.4.16          
cffi                         1.11.1             
chardet                      3.0.4              
click                        6.7                
colorama                     0.3.9              
colored-traceback            0.3.0              
comar                        2.4.7              
configobj                    4.7.2              
configparser                 3.5.0              
cryptography                 2.2.1              
docker                       2.6.1              
docker-pycreds               0.2.1              
dockerpty                    0.4.1              
docopt                       0.6.2              
doflicky                     6                  
enum34                       1.1.6              
Flask                        1.0.2              
functools32                  3.2.3.post2        
future                       0.16.0             
futures                      3.2.0              
gevent                       1.3.4              
gpg                          1.10.0             
greenlet                     0.4.13             
idna                         2.5                
ipaddr                       2.1.11             
ipaddress                    1.0.22             
itsdangerous                 0.24               
jedi                         0.12.0             
Jinja2                       2.10               
jsonschema                   2.6.0              
libvirt-python               4.3.0              
locustio                     0.8.1              
lxml                         4.0.0              
MarkupSafe                   1.0                
mccabe                       0.6.1              
msgpack-python               0.5.6              
mutagen                      1.40.0             
olefile                      0.45.1             
packaging                    16.8               
parse                        1.8.2              
parso                        0.2.0              
piksemel                     1.3.1              
Pillow                       4.3.0              
pip                          10.0.1             
pisi                         3.2                
pluggy                       0.6.0              
pwquality                    1.4.0              
pyasn1                       0.4.2              
pycairo                      1.14.1             
pycodestyle                  2.4.0              
pycparser                    2.18               
pycups                       1.9.73             
pycurl                       7.19.0             
pydocstyle                   2.1.1              
pyflakes                     1.6.0              
pygeoip                      0.2.7              
Pygments                     2.2.0              
pygobject                    3.28.2             
pyliblzma                    0.5.3              
pyls                         0.1.3              
pyOpenSSL                    17.5.0             
pyparsing                    2.0.6              
pyparted                     3.10.7             
PySocks                      1.6.7              
python-language-server       0.18.0             
python-magic                 0.4.3              
PyYAML                       3.12               
pyzmq                        17.0.0             
requests                     2.18.4             
rope                         0.10.7             
ruamel.ordereddict           0.4.9              
ruamel.yaml                  0.11.11            
setuptools                   38.2.5.post20180123
six                          1.11.0             
snowballstemmer              1.2.1              
solus-sc                     20.0               
texttable                    0.9.0              
urlgrabber                   3.10.1             
urllib3                      1.22               
variety                      0.6.9              
virtualenv                   15.2.0             
websocket-client             0.46.0             
Werkzeug                     0.14.1             
yapf                         0.21.0             
ypkg2                        27.0.0
```

**Comment by gatesn** [comment]
Please re-open if you're still seeing this issue

**Comment by bimsoft** [comment]
What is solution of this? This same error i am getting during running git pull-request?
