### ISSUE TITLE
Jedi: line not in valid range

### ISSUE THREAD

**Issue by languitar** [palantir/python-language-server#343]
With the recent change to the new Jedi version I am starting to see crashes of the language server like this one:
```
2018-05-02 14:59:24,937 UTC - ERROR - pyls.jsonrpc.endpoint - Failed to handle request 3404
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pyls/jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/usr/lib/python3.6/site-packages/pyls/jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "/usr/lib/python3.6/site-packages/pyls/jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/usr/lib/python3.6/site-packages/pyls/python_ls.py", line 236, in m_text_document__completion
    return self.completions(textDocument['uri'], position)
  File "/usr/lib/python3.6/site-packages/pyls/python_ls.py", line 167, in completions
    completions = self._hook('pyls_completions', doc_uri, position=position)
  File "/usr/lib/python3.6/site-packages/pyls/python_ls.py", line 113, in _hook
    return hook_handlers(config=self.config, workspace=self.workspace, document=doc, **kwargs)
  File "/usr/lib/python3.6/site-packages/pluggy/__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/usr/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib/python3.6/site-packages/pluggy/__init__.py", line 182, in __call__
    return outcome.get_result()
  File "/usr/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3.6/site-packages/pluggy/callers.py", line 48, in from_call
    result = func()
  File "/usr/lib/python3.6/site-packages/pluggy/__init__.py", line 180, in <lambda>
    outcome = _Result.from_call(lambda: self.oldcall(hook, hook_impls, kwargs))
  File "/usr/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/usr/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
    return outcome.get_result()
  File "/usr/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/usr/lib/python3.6/site-packages/pyls/plugins/jedi_completion.py", line 10, in pyls_completions
    definitions = document.jedi_script(position).completions()
  File "/usr/lib/python3.6/site-packages/pyls/workspace.py", line 264, in jedi_script
    return jedi.Script(**kwargs)
  File "/usr/lib/python3.6/site-packages/jedi/api/__init__.py", line 126, in __init__
    raise ValueError('`line` parameter is not in a valid range.')
```

I have also upgraded the neovim client, so I can't tell for sure who is the real cause of this, but the logs of the client indicate that the server itself is the issue:
```
Message: {"jsonrpc":"2.0","method":"languageClient/omniComplete","params":{"buftype":"","character":48,"filename":"/home/languitar/src/autosuspend/test_autosuspend.py","handle":false,"languageId":"python","line":1309},"id":148}

Error: ErrorMessage { msg: "ValueError: `line` parameter is not in a valid range." }
14:59:24 ERROR main src/vim.rs:57 Error handling message: ValueError: `line` parameter is not in a valid range.
```

That source file has much more lines than 1309. So this can't be just an off by one error or something like that.

**Comment by languitar** [comment]
This is appearing really often now and makes the server pretty useless for me atm. Any chance to find out what is going on here?

**Comment by gatesn** [comment]
@languitar can you provide the full pyls logs by running with `pyls -vv`? Note the contents of the file will be in those logs, feel free to redact them.

Also is there a particular file that you could link to where you see this issue? Is it deterministic?

**Comment by languitar** [comment]
I'll try to reproduce this tomorrow with more logging. This happened on different projects and different files.

**Comment by languitar** [comment]
Great, with full logging this doesn't seem to happen :/

**Comment by vv111y** [comment]
Any news on this? I have this issue too

**Comment by TakaakiFuruse** [comment]
I had the same issue.
What I did was just upgrade jedi to 0.16.0  forcefully by 

```
pip install 'python-language-server[all]'
pip install --upgrade jedi
```

The problem has just gone (I know this isn't a good thing).
