### ISSUE TITLE
KeyError in didClose call

### ISSUE THREAD

**Issue by languitar** [palantir/python-language-server#369]
With the neovim client I am recently seeing this exception quite often:

```
2018-06-02 17:38:52,617 UTC - DEBUG - pyls.jsonrpc.endpoint - Handling notification from client {'jsonrpc': '2.0', 'method': 'textDocument/didSave', 'params': {'textDocument': {'uri': 'file:///home/languitar/src/autosuspend/tests/test_checks_util.py'}}}
2018-06-02 17:39:19,679 UTC - DEBUG - pyls.jsonrpc.endpoint - Handling notification from client {'jsonrpc': '2.0', 'method': 'textDocument/didClose', 'params': {'textDocument': {'uri': 'file:///home/languitar/src/autosuspend/tests/test_checks_util.py'}}}
2018-06-02 17:39:19,679 UTC - ERROR - pyls.jsonrpc.endpoint - Failed to handle notification textDocument/didClose: {'textDocument': {'uri': 'file:///home/languitar/src/autosuspend/tests/test_checks_util.py'}}
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pyls/jsonrpc/endpoint.py", line 142, in _handle_notification
    handler_result = handler(params)
  File "/usr/lib/python3.6/site-packages/pyls/jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/usr/lib/python3.6/site-packages/pyls/python_ls.py", line 210, in m_text_document__did_close
    self.workspace.rm_document(textDocument['uri'])
  File "/usr/lib/python3.6/site-packages/pyls/workspace.py", line 124, in rm_document
    self._docs.pop(doc_uri)
KeyError: 'file:///home/languitar/src/autosuspend/tests/test_checks_util.py'
```

Unfortunately, the log file got truncated by the client to a fixed size, so there is no trace from the beginning of the server process.

**Comment by languitar** [comment]
Maybe this log is a bit more complete:

```
2018-06-02 17:40:38,056 UTC - DEBUG - pyls.config.source - Using cached configuration for ()
2018-06-02 17:40:38,056 UTC - DEBUG - pyls.config.config - Got user config from PyCodeStyleConfig: {}
2018-06-02 17:40:38,056 UTC - DEBUG - pyls.config.config - With user configuration: {}
2018-06-02 17:40:38,056 UTC - DEBUG - pyls.config.config - With plugin configuration: {'plugins': {'pydocstyle': {'enabled': False}, 'rope_completion': {'enabled': False}}}
2018-06-02 17:40:38,056 UTC - DEBUG - pyls.config.config - With lsp configuration: {'plugins': {'pydocstyle': {'enabled': False}, 'rope_completion': {'enabled': False}}}
2018-06-02 17:40:38,056 UTC - DEBUG - pyls.config.source - Using cached configuration for ('/home/languitar/src/autosuspend/setup.cfg', '/home/languitar/src/autosuspend/tox.ini')
2018-06-02 17:40:38,056 UTC - DEBUG - pyls.config.config - Got project config from PyCodeStyleConfig: {}
2018-06-02 17:40:38,057 UTC - DEBUG - pyls.config.config - With project configuration: {'plugins': {'pydocstyle': {'enabled': False}, 'rope_completion': {'enabled': False}}}
2018-06-02 17:40:38,057 UTC - DEBUG - pyls.plugins.pycodestyle_lint - Got pycodestyle settings: {}
2018-06-02 17:40:38,113 UTC - DEBUG - pyls.config.source - Using cached configuration for ()
2018-06-02 17:40:38,113 UTC - DEBUG - pyls.config.config - Got user config from PyCodeStyleConfig: {}
2018-06-02 17:40:38,113 UTC - DEBUG - pyls.config.config - With user configuration: {}
2018-06-02 17:40:38,114 UTC - DEBUG - pyls.config.config - With plugin configuration: {'plugins': {'pydocstyle': {'enabled': False}, 'rope_completion': {'enabled': False}}}
2018-06-02 17:40:38,114 UTC - DEBUG - pyls.config.config - With lsp configuration: {'plugins': {'pydocstyle': {'enabled': False}, 'rope_completion': {'enabled': False}}}
2018-06-02 17:40:38,114 UTC - DEBUG - pyls.config.source - Using cached configuration for ('/home/languitar/src/autosuspend/setup.cfg', '/home/languitar/src/autosuspend/tox.ini')
2018-06-02 17:40:38,114 UTC - DEBUG - pyls.config.config - Got project config from PyCodeStyleConfig: {}
2018-06-02 17:40:38,114 UTC - DEBUG - pyls.config.config - With project configuration: {'plugins': {'pydocstyle': {'enabled': False}, 'rope_completion': {'enabled': False}}}
2018-06-02 17:40:38,114 UTC - DEBUG - pyls.plugins.mccabe_lint - Running mccabe lint with threshold: 15
2018-06-02 17:40:38,128 UTC - DEBUG - pyls.config.config -   finish pyls_lint --> [[], [], [], [{'source': 'mypy', 'range': {'start': {'line': 3, 'character': 1}, 'end': {'line': 3, 'character': 2}}, 'message': 'No parent module -- cannot perform relative import', 'severity': 1}]] [hook]

2018-06-02 17:40:38,128 UTC - DEBUG - pyls.jsonrpc.endpoint - Sending notification: textDocument/publishDiagnostics {'uri': 'file:///home/languitar/src/autosuspend/src/autosuspend/checks/util.py', 'diagnostics': [{'source': 'mypy', 'range': {'start': {'line': 3, 'character': 1}, 'end': {'line': 3, 'character': 2}}, 'message': 'No parent module -- cannot perform relative import', 'severity': 1}]}
2018-06-02 17:40:41,455 UTC - DEBUG - pyls.jsonrpc.endpoint - Handling notification from client {'jsonrpc': '2.0', 'method': 'textDocument/didClose', 'params': {'textDocument': {'uri': 'file:///home/languitar/src/autosuspend/tests/test_checks_util.py'}}}
2018-06-02 17:40:41,455 UTC - ERROR - pyls.jsonrpc.endpoint - Failed to handle notification textDocument/didClose: {'textDocument': {'uri': 'file:///home/languitar/src/autosuspend/tests/test_checks_util.py'}}
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pyls/jsonrpc/endpoint.py", line 142, in _handle_notification
    handler_result = handler(params)
  File "/usr/lib/python3.6/site-packages/pyls/jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/usr/lib/python3.6/site-packages/pyls/python_ls.py", line 210, in m_text_document__did_close
    self.workspace.rm_document(textDocument['uri'])
  File "/usr/lib/python3.6/site-packages/pyls/workspace.py", line 124, in rm_document
    self._docs.pop(doc_uri)
KeyError: 'file:///home/languitar/src/autosuspend/tests/test_checks_util.py'
```

**Comment by gatesn** [comment]
Please re-open if you're still seeing this issue

**Comment by joshbode** [comment]
I'm still getting this in the `pyls` logs on `python-language-server==0.26.1`:
```
2019-04-14 22:41:13,959 UTC - ERROR - pyls_jsonrpc.endpoint - Failed to handle notification textDocument/didClose: {'textDocument': {'uri': 'file:///home/josh/inflate.py'}}
Traceback (most recent call last):
  File "/home/josh/.virtualenvs/default/lib/python3.7/site-packages/pyls_jsonrpc/endpoint.py", line 142, in _handle_notification
    handler_result = handler(params)
  File "/home/josh/.virtualenvs/default/lib/python3.7/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/home/josh/.virtualenvs/default/lib/python3.7/site-packages/pyls/python_ls.py", line 240, in m_text_document__did_close
    self.workspace.rm_document(textDocument['uri'])
  File "/home/josh/.virtualenvs/default/lib/python3.7/site-packages/pyls/workspace.py", line 74, in rm_document
    self._docs.pop(doc_uri)
KeyError: 'file:///home/josh/inflate.py'
```
