### ISSUE TITLE
Cannot install pyls from pip due to SSL error

### ISSUE THREAD

**Issue by lewis6991** [palantir/python-language-server#395]
```
$ pip3 install pyls
Collecting pyls
  Downloading https://files.pythonhosted.org/packages/de/b7/5a056c2cac8fd19c905ae7451c2a60b9195531959c3770a49d6be4d905e3/pyls-0.1.3.zip
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.14.tar.gz
    Traceback (most recent call last):
      File "/tmp/pip-install-swr2ndpi/pyls/setup_utils/distribute_setup.py", line 143, in use_setuptools
        raise ImportError
    ImportError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-swr2ndpi/pyls/setup.py", line 31, in <module>
        main()
      File "/tmp/pip-install-swr2ndpi/pyls/setup.py", line 11, in main
        distribute_setup.use_setuptools()
      File "/tmp/pip-install-swr2ndpi/pyls/setup_utils/distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "/tmp/pip-install-swr2ndpi/pyls/setup_utils/distribute_setup.py", line 124, in _do_download
        to_dir, download_delay)
      File "/tmp/pip-install-swr2ndpi/pyls/setup_utils/distribute_setup.py", line 193, in download_setuptools
        src = urlopen(url)
      File ".../opt/python/lib/python3.7/urllib/request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
      File ".../opt/python/lib/python3.7/urllib/request.py", line 531, in open
        response = meth(req, response)
      File ".../opt/python/lib/python3.7/urllib/request.py", line 641, in http_response
        'http', request, response, code, msg, hdrs)
      File ".../opt/python/lib/python3.7/urllib/request.py", line 569, in error
        return self._call_chain(*args)
      File ".../opt/python/lib/python3.7/urllib/request.py", line 503, in _call_chain
        result = func(*args)
      File ".../opt/python/lib/python3.7/urllib/request.py", line 649, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 403: SSL is required

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-swr2ndpi/pyls/
```

I am only getting this error when trying to install pyls. No other packages I have installed report this error.

**Comment by lewis6991** [comment]
False alarm, I was trying to pip install `pyls` instead of `python-language-server`
