### ISSUE TITLE
Pyls autocomplete crash

### ISSUE THREAD

**Issue by benschlueter** [palantir/python-language-server#444]
Hello,
I guess its a pyls or jedi issue.
The issue happened the first time after I write os. after the dot no completion windows pop up and i got the error message.
And after the error occurs I get no more completions from pyls. I have to restart sublime.

> Type Error, argument 1 must be str, not bytes

Here is the Detail log

> LSP: severity check 2 <= 3
LSP: --> textDocument/didChange
LSP: --> textDocument/completion
server: 2018-10-30 08:04:29,159 UTC - ERROR - jsonrpc.endpoint - Failed to handle request 3
server: Traceback (most recent call last):
server: File "/usr/lib/python3.7/site-packages/jsonrpc/endpoint.py", line 113, in consume
server: self._handle_request(message['id'], message['method'], message.get('params'))
server: File "/usr/lib/python3.7/site-packages/jsonrpc/endpoint.py", line 182, in _handle_request
server: handler_result = handler(params)
server: File "/usr/lib/python3.7/site-packages/jsonrpc/dispatchers.py", line 23, in handler
server: return method(**(params or {}))
server: File "/usr/lib/python3.7/site-packages/pyls/python_ls.py", line 257, in m_text_document__completion
server: return self.completions(textDocument['uri'], position)
server: File "/usr/lib/python3.7/site-packages/pyls/python_ls.py", line 185, in completions
server: completions = self._hook('pyls_completions', doc_uri, position=position)
server: File "/usr/lib/python3.7/site-packages/pyls/python_ls.py", line 117, in _hook
server: return hook_handlers(config=self.config, workspace=self.workspace, document=doc, **kwargs)
server: File "/usr/lib/python3.7/site-packages/pluggy/hooks.py", line 258, in call
server: return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
server: File "/usr/lib/python3.7/site-packages/pluggy/manager.py", line 67, in _hookexec
server: return self._inner_hookexec(hook, methods, kwargs)
server: File "/usr/lib/python3.7/site-packages/pluggy/_tracing.py", line 82, in call
server: return outcome.get_result()
server: File "/usr/lib/python3.7/site-packages/pluggy/callers.py", line 76, in get_result
server: raise ex[1].with_traceback(ex[2])
server: File "/usr/lib/python3.7/site-packages/pluggy/callers.py", line 48, in from_call
server: result = func()
server: File "/usr/lib/python3.7/site-packages/pluggy/_tracing.py", line 80, in 
server: outcome = _Result.from_call(lambda: self.oldcall(hook, hook_impls, kwargs))
server: File "/usr/lib/python3.7/site-packages/pluggy/manager.py", line 61, in 
server: firstresult=hook.spec_opts.get('firstresult'),
server: File "/usr/lib/python3.7/site-packages/pluggy/callers.py", line 201, in _multicall
server: return outcome.get_result()
server: File "/usr/lib/python3.7/site-packages/pluggy/callers.py", line 76, in get_result
server: raise ex[1].with_traceback(ex[2])
server: File "/usr/lib/python3.7/site-packages/pluggy/callers.py", line 180, in _multicall
server: res = hook_impl.function(*args)
server: File "/usr/lib/python3.7/site-packages/pyls/plugins/jedi_completion.py", line 10, in pyls_completions
server: definitions = document.jedi_script(position).completions()
server: File "/usr/lib/python3.7/site-packages/jedi/api/init.py", line 174, in completions
server: completions = completion.completions()
server: File "/usr/lib/python3.7/site-packages/jedi/api/completion.py", line 98, in completions
server: completion_names = self._get_context_completions()
server: File "/usr/lib/python3.7/site-packages/jedi/api/completion.py", line 198, in _get_context_completions
server: completion_names += self._trailer_completions(dot.get_previous_leaf())
server: File "/usr/lib/python3.7/site-packages/jedi/api/completion.py", line 234, in _trailer_completions
server: contexts = evaluate_call_of_leaf(evaluation_context, previous_leaf)
server: File "/usr/lib/python3.7/site-packages/jedi/evaluate/helpers.py", line 73, in evaluate_call_of_leaf
server: return context.eval_node(leaf)
server: File "/usr/lib/python3.7/site-packages/jedi/evaluate/base_context.py", line 145, in eval_node
server: return self.evaluator.eval_element(self, node)
server: File "/usr/lib/python3.7/site-packages/jedi/evaluate/init.py", line 194, in eval_element
server: return self._eval_element_if_evaluated(context, element)
server: File "/usr/lib/python3.7/site-packages/jedi/evaluate/init.py", line 206, in _eval_element_if_evaluated
server: return self._eval_element_cached(context, element)
server: File "/usr/lib/python3.7/site-packages/jedi/evaluate/cache.py", line 40, in wrapper
server: rv = function(obj, *args, **kwargs)
server: File "/usr/lib/python3.7/site-packages/jedi/evaluate/init.py", line 210, in eval_element_cached
server: return eval_node(context, element)
server: File "/usr/lib/python3.7/site-packages/jedi/debug.py", line 79, in wrapper
server: return func(*args, **kwargs)
server: File "/usr/lib/python3.7/site-packages/jedi/evaluate/syntax_tree.py", line 48, in wrapper
server: return func(context, *args, **kwargs)
server: File "/usr/lib/python3.7/site-packages/jedi/evaluate/syntax_tree.py", line 72, in eval_node
server: return eval_atom(context, element)
server: File "/usr/lib/python3.7/site-packages/jedi/evaluate/syntax_tree.py", line 202, in eval_atom
server: search_global=True
server: File "/usr/lib/python3.7/site-packages/jedi/compatibility.py", line 263, in 
server: return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
server: File "/usr/lib/python3.7/site-packages/jedi/evaluate/base_context.py", line 162, in py__getattribute
server: return f.find(filters, attribute_lookup=not search_global)
server: File "/usr/lib/python3.7/site-packages/jedi/debug.py", line 79, in wrapper
server: return func(*args, **kwargs)
server: File "/usr/lib/python3.7/site-packages/jedi/evaluate/finder.py", line 67, in find
server: types = self._names_to_types(names, attribute_lookup)
server: File "/usr/lib/python3.7/site-packages/jedi/evaluate/finder.py", line 178, in _names_to_types
server: contexts = ContextSet.from_sets(name.infer() for name in names)
server: File "/usr/lib/python3.7/site-packages/jedi/common/context.py", line 34, in from_sets
server: sets = list(sets)
server: File "/usr/lib/python3.7/site-packages/jedi/evaluate/finder.py", line 178, in 
server: contexts = ContextSet.from_sets(name.infer() for name in names)
server: File "/usr/lib/python3.7/site-packages/jedi/evaluate/filters.py", line 108, in infer
server: return tree_name_to_contexts(self.parent_context.evaluator, self.parent_context, self.tree_name)
server: File "/usr/lib/python3.7/site-packages/jedi/evaluate/syntax_tree.py", line 560, in tree_name_to_contexts
server: types = imports.infer_import(context, tree_name)
server: File "/usr/lib/python3.7/site-packages/jedi/evaluate/cache.py", line 40, in wrapper
server: rv = function(obj, *args, **kwargs)
server: File "/usr/lib/python3.7/site-packages/jedi/evaluate/imports.py", line 79, in infer_import
server: types = importer.follow()
server: File "/usr/lib/python3.7/site-packages/jedi/evaluate/imports.py", line 280, in follow
server: return self._do_import(self.import_path, self.sys_path_with_modifications())
server: File "/usr/lib/python3.7/site-packages/jedi/evaluate/imports.py", line 358, in _do_import
server: sys_path=sys_path,
server: File "/usr/lib/python3.7/site-packages/jedi/evaluate/compiled/subprocess/init.py", line 94, in wrapper
server: kwargs=kwargs,
server: File "/usr/lib/python3.7/site-packages/jedi/evaluate/compiled/subprocess/init.py", line 166, in run
server: return self._send(id(evaluator), function, args, kwargs)
server: File "/usr/lib/python3.7/site-packages/jedi/evaluate/compiled/subprocess/init.py", line 210, in _send
server: is_exception, traceback, result = pickle_load(self._process.stdout)
server: File "/usr/lib/python3.7/site-packages/jedi/_compatibility.py", line 452, in pickle_load
server: return pickle.load(file, encoding='bytes')
server: TypeError: argument 1 must be str, not bytes
LSP: <-- textDocument/publishDiagnostics

>

**Comment by benschlueter** [comment]
Old pyls and jedi caused the issue. Deleted and reinstalled via pacman solved it
