### ISSUE TITLE
ImportError: cannot import name 'install_aliases' from 'future.standard_library'

### ISSUE THREAD

**Issue by lqmanh** [palantir/python-language-server#446]
When I tried to run `pyls` from command line, I encountered this issue. Below is the full traceback:
```
Traceback (most recent call last):
  File "/usr/bin/pyls", line 11, in <module>
    load_entry_point('python-language-server==0.21.2', 'console_scripts', 'pyls')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2725, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2343, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2349, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/pyls/__init__.py", line 3, in <module>
    from future.standard_library import install_aliases
ImportError: cannot import name 'install_aliases' from 'future.standard_library' (/usr/lib/python3.7/site-packages/future/standard_library/__init__.py)
```

**Comment by DyLanCao** [comment]
I encountered the same question. Do you  have answer?

**Comment by lqmanh** [comment]
@DyLanCao I don't know. I don't use this anymore, unfortunately.
