### ISSUE TITLE
Installing via pip

### ISSUE THREAD

**Issue by nordlow** [palantir/python-language-server#45]
Is it possible to install pyls via pip?

A call to `pip install --user pyls`

fails as

```
Collecting pyls
  Downloading pyls-0.1.3.zip
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.14.tar.gz
    Extracting in /tmp/tmpTC5h_r
    Now working in /tmp/tmpTC5h_r/distribute-0.6.14
    Building a Distribute egg in /tmp/pip-build-NGPQpl/pyls
    Traceback (most recent call last):
      File "setup.py", line 37, in <module>
        exec(open(init_path).read(), d)
      File "<string>", line 8, in <module>
      File "/tmp/tmpTC5h_r/distribute-0.6.14/setuptools/__init__.py", line 2, in <module>
        from setuptools.extension import Extension, Library
      File "/tmp/tmpTC5h_r/distribute-0.6.14/setuptools/extension.py", line 2, in <module>
        from setuptools.dist import _get_unpatched
      File "/tmp/tmpTC5h_r/distribute-0.6.14/setuptools/dist.py", line 6, in <module>
        from setuptools.command.install import install
      File "/tmp/tmpTC5h_r/distribute-0.6.14/setuptools/command/__init__.py", line 8, in <module>
        from setuptools.command import install_scripts
      File "/tmp/tmpTC5h_r/distribute-0.6.14/setuptools/command/install_scripts.py", line 3, in <module>
        from pkg_resources import Distribution, PathMetadata, ensure_directory
      File "/tmp/tmpTC5h_r/distribute-0.6.14/pkg_resources.py", line 2691, in <module>
        add_activation_listener(lambda dist: dist.activate())
      File "/tmp/tmpTC5h_r/distribute-0.6.14/pkg_resources.py", line 668, in subscribe
        callback(dist)
      File "/tmp/tmpTC5h_r/distribute-0.6.14/pkg_resources.py", line 2691, in <lambda>
        add_activation_listener(lambda dist: dist.activate())
      File "/tmp/tmpTC5h_r/distribute-0.6.14/pkg_resources.py", line 2192, in activate
        self.insert_on(path)
      File "/tmp/tmpTC5h_r/distribute-0.6.14/pkg_resources.py", line 2293, in insert_on
        "with distribute. Found one at %s" % str(self.location))
    ValueError: A 0.7-series setuptools cannot be installed with distribute. Found one at /usr/lib/python2.7/dist-packages
    /tmp/pip-build-NGPQpl/pyls/distribute-0.6.14-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-NGPQpl/pyls/setup.py", line 31, in <module>
        main()
      File "/tmp/pip-build-NGPQpl/pyls/setup.py", line 11, in main
        distribute_setup.use_setuptools()
      File "setup_utils/distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "setup_utils/distribute_setup.py", line 125, in _do_download
        _build_egg(egg, tarball, to_dir)
      File "setup_utils/distribute_setup.py", line 116, in _build_egg
        raise IOError('Could not build the egg.')
    IOError: Could not build the egg.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-NGPQpl/pyls/
```

and to `pip3 install --user pyls`

fails as

```
Collecting pyls
  Using cached pyls-0.1.3.zip
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.14.tar.gz
    Extracting in /tmp/tmp5zufnl0r
    Traceback (most recent call last):
      File "/tmp/pip-build-ldrp9vpf/pyls/setup_utils/distribute_setup.py", line 143, in use_setuptools
        raise ImportError
    ImportError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ldrp9vpf/pyls/setup.py", line 31, in <module>
        main()
      File "/tmp/pip-build-ldrp9vpf/pyls/setup.py", line 11, in main
        distribute_setup.use_setuptools()
      File "/tmp/pip-build-ldrp9vpf/pyls/setup_utils/distribute_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "/tmp/pip-build-ldrp9vpf/pyls/setup_utils/distribute_setup.py", line 125, in _do_download
        _build_egg(egg, tarball, to_dir)
      File "/tmp/pip-build-ldrp9vpf/pyls/setup_utils/distribute_setup.py", line 99, in _build_egg
        _extractall(tar)
      File "/tmp/pip-build-ldrp9vpf/pyls/setup_utils/distribute_setup.py", line 467, in _extractall
        self.chown(tarinfo, dirpath)
    TypeError: chown() missing 1 required positional argument: 'numeric_owner'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ldrp9vpf/pyls/
```

**Comment by gatesn** [comment]
Thanks for reporting this, we don't actually publish to PyPi right now. Going to close this in favour of #9 

I think there happens to be another package called pyls, it's not this one.
