### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by evandrocoan** [palantir/python-language-server#463]
```
14:46:03:954.191923 1.52e+00 - LSP.plugin.core.rpc.send_request:94 -  --> textDocument/definition
14:46:03:954.692602 2.62e+00 - pyls.python_ls._hook:126 DEBUG - PythonLanguageServer, self.config: Config. _root_path: f:\SublimeText\Data, _root_uri: file:///F:/SublimeText/Data, _init_opts: {}, _settings: {'plugins': {'pycodestyle': {'enabled': False}, 'rope': {'ropeFolder': None}, 'pydocstyle': {'ignore': ['D200', 'D202', 'D204', 'D205', 'D208', 'D400', 'D401'], 'enabled': False}}}, _plugin_settings: {'plugins': {'rope_completion': {'enabled': False}, 'pydocstyle': {'enabled': False}, 'preload': {'modules': ['OpenGL', 'PIL', 'array', 'audioop', 'binascii', 'cPickle', 'cStringIO', 'cmath', 'collections', 'datetime', 'errno', 'exceptions', 'gc', 'imageop', 'imp', 'itertools', 'marshal', 'math', 'matplotlib', 'mmap', 'mpmath', 'msvcrt', 'networkx', 'nose', 'nt', 'numpy', 'operator', 'os', 'os.path', 'pandas', 'parser', 'rgbimg', 'scipy', 'signal', 'skimage', 'sklearn', 'statsmodels', 'strop', 'sympy', 'sys', 'thread', 'time', 'wx', 'xxsubtype', 'zipimport', 'zlib']}}, 'rope': {'extensionModules': ['OpenGL', 'PIL', 'array', 'audioop', 'binascii', 'cPickle', 'cStringIO', 'cmath', 'collections', 'datetime', 'errno', 'exceptions', 'gc', 'imageop', 'imp', 'itertools', 'marshal', 'math', 'matplotlib', 'mmap', 'mpmath', 'msvcrt', 'networkx', 'nose', 'nt', 'numpy', 'operator', 'os', 'os.path', 'pandas', 'parser', 'rgbimg', 'scipy', 'signal', 'skimage', 'sklearn', 'statsmodels', 'strop', 'sympy', 'sys', 'thread', 'time', 'wx', 'xxsubtype', 'zipimport', 'zlib']}}, self.settings(): {'plugins': {'rope_completion': {'enabled': False}, 'preload': {'modules': ['OpenGL', 'PIL', 'array', 'audioop', 'binascii', 'cPickle', 'cStringIO', 'cmath', 'collections', 'datetime', 'errno', 'exceptions', 'gc', 'imageop', 'imp', 'itertools', 'marshal', 'math', 'matplotlib', 'mmap', 'mpmath', 'msvcrt', 'networkx', 'nose', 'nt', 'numpy', 'operator', 'os', 'os.path', 'pandas', 'parser', 'rgbimg', 'scipy', 'signal', 'skimage', 'sklearn', 'statsmodels', 'strop', 'sympy', 'sys', 'thread', 'time', 'wx', 'xxsubtype', 'zipimport', 'zlib']}, 'pycodestyle': {'enabled': False}, 'pydocstyle': {'ignore': ['D200', 'D202', 'D204', 'D205', 'D208', 'D400', 'D401'], 'enabled': False}, 'rope': {'ropeFolder': None}}, 'rope': {'extensionModules': ['OpenGL', 'PIL', 'array', 'audioop', 'binascii', 'cPickle', 'cStringIO', 'cmath', 'collections', 'datetime', 'errno', 'exceptions', 'gc', 'imageop', 'imp', 'itertools', 'marshal', 'math', 'matplotlib', 'mmap', 'mpmath', 'msvcrt', 'networkx', 'nose', 'nt', 'numpy', 'operator', 'os', 'os.path', 'pandas', 'parser', 'rgbimg', 'scipy', 'signal', 'skimage', 'sklearn', 'statsmodels', 'strop', 'sympy', 'sys', 'thread', 'time', 'wx', 'xxsubtype', 'zipimport', 'zlib']}}, _config_sources(flake8): Flake8Config. root_path: f:\SublimeText\Data, is_windows: True, xdg_home: C:\Users\Professional/.config, _modified_times: {}, _config_sources(pycodestyle): PyCodeStyleConfig. root_path: f:\SublimeText\Data, is_windows: True, xdg_home: C:\Users\Professional/.config, _modified_times: {(): ()}, _configs_cache(()): []
14:46:03:956.692219 1.52e+00 - pyls.config.config.processmessage:137 DEBUG -   pyls_definitions [hook]
      config: Config. _root_path: f:\SublimeText\Data, _root_uri: file:///F:/SublimeText/Data, _init_opts: {}, _settings: {'plugins': {'pycodestyle': {'enabled': False}, 'rope': {'ropeFolder': None}, 'pydocstyle': {'ignore': ['D200', 'D202', 'D204', 'D205', 'D208', 'D400', 'D401'], 'enabled': False}}}, _plugin_settings: {'plugins': {'rope_completion': {'enabled': False}, 'pydocstyle': {'enabled': False}, 'preload': {'modules': ['OpenGL', 'PIL', 'array', 'audioop', 'binascii', 'cPickle', 'cStringIO', 'cmath', 'collections', 'datetime', 'errno', 'exceptions', 'gc', 'imageop', 'imp', 'itertools', 'marshal', 'math', 'matplotlib', 'mmap', 'mpmath', 'msvcrt', 'networkx', 'nose', 'nt', 'numpy', 'operator', 'os', 'os.path', 'pandas', 'parser', 'rgbimg', 'scipy', 'signal', 'skimage', 'sklearn', 'statsmodels', 'strop', 'sympy', 'sys', 'thread', 'time', 'wx', 'xxsubtype', 'zipimport', 'zlib']}}, 'rope': {'extensionModules': ['OpenGL', 'PIL', 'array', 'audioop', 'binascii', 'cPickle', 'cStringIO', 'cmath', 'collections', 'datetime', 'errno', 'exceptions', 'gc', 'imageop', 'imp', 'itertools', 'marshal', 'math', 'matplotlib', 'mmap', 'mpmath', 'msvcrt', 'networkx', 'nose', 'nt', 'numpy', 'operator', 'os', 'os.path', 'pandas', 'parser', 'rgbimg', 'scipy', 'signal', 'skimage', 'sklearn', 'statsmodels', 'strop', 'sympy', 'sys', 'thread', 'time', 'wx', 'xxsubtype', 'zipimport', 'zlib']}}, self.settings(): {'plugins': {'rope_completion': {'enabled': False}, 'preload': {'modules': ['OpenGL', 'PIL', 'array', 'audioop', 'binascii', 'cPickle', 'cStringIO', 'cmath', 'collections', 'datetime', 'errno', 'exceptions', 'gc', 'imageop', 'imp', 'itertools', 'marshal', 'math', 'matplotlib', 'mmap', 'mpmath', 'msvcrt', 'networkx', 'nose', 'nt', 'numpy', 'operator', 'os', 'os.path', 'pandas', 'parser', 'rgbimg', 'scipy', 'signal', 'skimage', 'sklearn', 'statsmodels', 'strop', 'sympy', 'sys', 'thread', 'time', 'wx', 'xxsubtype', 'zipimport', 'zlib']}, 'pycodestyle': {'enabled': False}, 'pydocstyle': {'ignore': ['D200', 'D202', 'D204', 'D205', 'D208', 'D400', 'D401'], 'enabled': False}, 'rope': {'ropeFolder': None}}, 'rope': {'extensionModules': ['OpenGL', 'PIL', 'array', 'audioop', 'binascii', 'cPickle', 'cStringIO', 'cmath', 'collections', 'datetime', 'errno', 'exceptions', 'gc', 'imageop', 'imp', 'itertools', 'marshal', 'math', 'matplotlib', 'mmap', 'mpmath', 'msvcrt', 'networkx', 'nose', 'nt', 'numpy', 'operator', 'os', 'os.path', 'pandas', 'parser', 'rgbimg', 'scipy', 'signal', 'skimage', 'sklearn', 'statsmodels', 'strop', 'sympy', 'sys', 'thread', 'time', 'wx', 'xxsubtype', 'zipimport', 'zlib']}}, _config_sources(flake8): Flake8Config. root_path: f:\SublimeText\Data, is_windows: True, xdg_home: C:\Users\Professional/.config, _modified_times: {}, _config_sources(pycodestyle): PyCodeStyleConfig. root_path: f:\SublimeText\Data, is_windows: True, xdg_home: C:\Users\Professional/.config, _modified_times: {(): ()}, _configs_cache(()): []
      workspace: Workspace. _root_path: f:\SublimeText\Data, _root_uri: file:///F:/SublimeText/Data, _root_uri_scheme: file, __rope: None, _docs(file:///F:/SublimeText/Data/Packages/MarkdownPreview/MarkdownPreview.py): Document. uri: file:///F:/SublimeText/Data/Packages/MarkdownPreview/MarkdownPreview.py, version: 12, path: f:\SublimeText\Data\Packages\MarkdownPreview\MarkdownPreview.py, filename: MarkdownPreview.py, _local: True, _extra_sys_path: []
      document: Document. uri: file:///F:/SublimeText/Data/Packages/MarkdownPreview/MarkdownPreview.py, version: 12, path: f:\SublimeText\Data\Packages\MarkdownPreview\MarkdownPreview.py, filename: MarkdownPreview.py, _local: True, _extra_sys_path: []
      position: {'line': 119, 'character': 67}

14:46:04:929.403543 9.73e-01 - pyls.config.config.processmessage:137 DEBUG -   finish pyls_definitions --> [[]] [hook]

14:46:04:929.902077 9.76e-01 - LSP.plugin.core.rpc.response_handler:160 -      []
14:46:05:466.469049 5.37e-01 - LSP.plugin.core.rpc.send_request:94 -  --> textDocument/references
14:46:05:466.977358 1.51e+00 - pyls.python_ls._hook:126 DEBUG - PythonLanguageServer, self.config: Config. _root_path: f:\SublimeText\Data, _root_uri: file:///F:/SublimeText/Data, _init_opts: {}, _settings: {'plugins': {'pycodestyle': {'enabled': False}, 'rope': {'ropeFolder': None}, 'pydocstyle': {'ignore': ['D200', 'D202', 'D204', 'D205', 'D208', 'D400', 'D401'], 'enabled': False}}}, _plugin_settings: {'plugins': {'rope_completion': {'enabled': False}, 'pydocstyle': {'enabled': False}, 'preload': {'modules': ['OpenGL', 'PIL', 'array', 'audioop', 'binascii', 'cPickle', 'cStringIO', 'cmath', 'collections', 'datetime', 'errno', 'exceptions', 'gc', 'imageop', 'imp', 'itertools', 'marshal', 'math', 'matplotlib', 'mmap', 'mpmath', 'msvcrt', 'networkx', 'nose', 'nt', 'numpy', 'operator', 'os', 'os.path', 'pandas', 'parser', 'rgbimg', 'scipy', 'signal', 'skimage', 'sklearn', 'statsmodels', 'strop', 'sympy', 'sys', 'thread', 'time', 'wx', 'xxsubtype', 'zipimport', 'zlib']}}, 'rope': {'extensionModules': ['OpenGL', 'PIL', 'array', 'audioop', 'binascii', 'cPickle', 'cStringIO', 'cmath', 'collections', 'datetime', 'errno', 'exceptions', 'gc', 'imageop', 'imp', 'itertools', 'marshal', 'math', 'matplotlib', 'mmap', 'mpmath', 'msvcrt', 'networkx', 'nose', 'nt', 'numpy', 'operator', 'os', 'os.path', 'pandas', 'parser', 'rgbimg', 'scipy', 'signal', 'skimage', 'sklearn', 'statsmodels', 'strop', 'sympy', 'sys', 'thread', 'time', 'wx', 'xxsubtype', 'zipimport', 'zlib']}}, self.settings(): {'plugins': {'rope_completion': {'enabled': False}, 'preload': {'modules': ['OpenGL', 'PIL', 'array', 'audioop', 'binascii', 'cPickle', 'cStringIO', 'cmath', 'collections', 'datetime', 'errno', 'exceptions', 'gc', 'imageop', 'imp', 'itertools', 'marshal', 'math', 'matplotlib', 'mmap', 'mpmath', 'msvcrt', 'networkx', 'nose', 'nt', 'numpy', 'operator', 'os', 'os.path', 'pandas', 'parser', 'rgbimg', 'scipy', 'signal', 'skimage', 'sklearn', 'statsmodels', 'strop', 'sympy', 'sys', 'thread', 'time', 'wx', 'xxsubtype', 'zipimport', 'zlib']}, 'pycodestyle': {'enabled': False}, 'pydocstyle': {'ignore': ['D200', 'D202', 'D204', 'D205', 'D208', 'D400', 'D401'], 'enabled': False}, 'rope': {'ropeFolder': None}}, 'rope': {'extensionModules': ['OpenGL', 'PIL', 'array', 'audioop', 'binascii', 'cPickle', 'cStringIO', 'cmath', 'collections', 'datetime', 'errno', 'exceptions', 'gc', 'imageop', 'imp', 'itertools', 'marshal', 'math', 'matplotlib', 'mmap', 'mpmath', 'msvcrt', 'networkx', 'nose', 'nt', 'numpy', 'operator', 'os', 'os.path', 'pandas', 'parser', 'rgbimg', 'scipy', 'signal', 'skimage', 'sklearn', 'statsmodels', 'strop', 'sympy', 'sys', 'thread', 'time', 'wx', 'xxsubtype', 'zipimport', 'zlib']}}, _config_sources(flake8): Flake8Config. root_path: f:\SublimeText\Data, is_windows: True, xdg_home: C:\Users\Professional/.config, _modified_times: {}, _config_sources(pycodestyle): PyCodeStyleConfig. root_path: f:\SublimeText\Data, is_windows: True, xdg_home: C:\Users\Professional/.config, _modified_times: {(): ()}, _configs_cache(()): []
14:46:05:468.975067 5.39e-01 - pyls.config.config.processmessage:137 DEBUG -   pyls_references [hook]
      config: Config. _root_path: f:\SublimeText\Data, _root_uri: file:///F:/SublimeText/Data, _init_opts: {}, _settings: {'plugins': {'pycodestyle': {'enabled': False}, 'rope': {'ropeFolder': None}, 'pydocstyle': {'ignore': ['D200', 'D202', 'D204', 'D205', 'D208', 'D400', 'D401'], 'enabled': False}}}, _plugin_settings: {'plugins': {'rope_completion': {'enabled': False}, 'pydocstyle': {'enabled': False}, 'preload': {'modules': ['OpenGL', 'PIL', 'array', 'audioop', 'binascii', 'cPickle', 'cStringIO', 'cmath', 'collections', 'datetime', 'errno', 'exceptions', 'gc', 'imageop', 'imp', 'itertools', 'marshal', 'math', 'matplotlib', 'mmap', 'mpmath', 'msvcrt', 'networkx', 'nose', 'nt', 'numpy', 'operator', 'os', 'os.path', 'pandas', 'parser', 'rgbimg', 'scipy', 'signal', 'skimage', 'sklearn', 'statsmodels', 'strop', 'sympy', 'sys', 'thread', 'time', 'wx', 'xxsubtype', 'zipimport', 'zlib']}}, 'rope': {'extensionModules': ['OpenGL', 'PIL', 'array', 'audioop', 'binascii', 'cPickle', 'cStringIO', 'cmath', 'collections', 'datetime', 'errno', 'exceptions', 'gc', 'imageop', 'imp', 'itertools', 'marshal', 'math', 'matplotlib', 'mmap', 'mpmath', 'msvcrt', 'networkx', 'nose', 'nt', 'numpy', 'operator', 'os', 'os.path', 'pandas', 'parser', 'rgbimg', 'scipy', 'signal', 'skimage', 'sklearn', 'statsmodels', 'strop', 'sympy', 'sys', 'thread', 'time', 'wx', 'xxsubtype', 'zipimport', 'zlib']}}, self.settings(): {'plugins': {'rope_completion': {'enabled': False}, 'preload': {'modules': ['OpenGL', 'PIL', 'array', 'audioop', 'binascii', 'cPickle', 'cStringIO', 'cmath', 'collections', 'datetime', 'errno', 'exceptions', 'gc', 'imageop', 'imp', 'itertools', 'marshal', 'math', 'matplotlib', 'mmap', 'mpmath', 'msvcrt', 'networkx', 'nose', 'nt', 'numpy', 'operator', 'os', 'os.path', 'pandas', 'parser', 'rgbimg', 'scipy', 'signal', 'skimage', 'sklearn', 'statsmodels', 'strop', 'sympy', 'sys', 'thread', 'time', 'wx', 'xxsubtype', 'zipimport', 'zlib']}, 'pycodestyle': {'enabled': False}, 'pydocstyle': {'ignore': ['D200', 'D202', 'D204', 'D205', 'D208', 'D400', 'D401'], 'enabled': False}, 'rope': {'ropeFolder': None}}, 'rope': {'extensionModules': ['OpenGL', 'PIL', 'array', 'audioop', 'binascii', 'cPickle', 'cStringIO', 'cmath', 'collections', 'datetime', 'errno', 'exceptions', 'gc', 'imageop', 'imp', 'itertools', 'marshal', 'math', 'matplotlib', 'mmap', 'mpmath', 'msvcrt', 'networkx', 'nose', 'nt', 'numpy', 'operator', 'os', 'os.path', 'pandas', 'parser', 'rgbimg', 'scipy', 'signal', 'skimage', 'sklearn', 'statsmodels', 'strop', 'sympy', 'sys', 'thread', 'time', 'wx', 'xxsubtype', 'zipimport', 'zlib']}}, _config_sources(flake8): Flake8Config. root_path: f:\SublimeText\Data, is_windows: True, xdg_home: C:\Users\Professional/.config, _modified_times: {}, _config_sources(pycodestyle): PyCodeStyleConfig. root_path: f:\SublimeText\Data, is_windows: True, xdg_home: C:\Users\Professional/.config, _modified_times: {(): ()}, _configs_cache(()): []
      workspace: Workspace. _root_path: f:\SublimeText\Data, _root_uri: file:///F:/SublimeText/Data, _root_uri_scheme: file, __rope: None, _docs(file:///F:/SublimeText/Data/Packages/MarkdownPreview/MarkdownPreview.py): Document. uri: file:///F:/SublimeText/Data/Packages/MarkdownPreview/MarkdownPreview.py, version: 12, path: f:\SublimeText\Data\Packages\MarkdownPreview\MarkdownPreview.py, filename: MarkdownPreview.py, _local: True, _extra_sys_path: []
      document: Document. uri: file:///F:/SublimeText/Data/Packages/MarkdownPreview/MarkdownPreview.py, version: 12, path: f:\SublimeText\Data\Packages\MarkdownPreview\MarkdownPreview.py, filename: MarkdownPreview.py, _local: True, _extra_sys_path: []
      position: {'line': 119, 'character': 67}
      exclude_declaration: True

Failed to handle request 23
Traceback (most recent call last):
  File "f:\python\lib\site-packages\jsonrpc\endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "f:\python\lib\site-packages\jsonrpc\endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "f:\python\lib\site-packages\jsonrpc\dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "d:\python-language-server\pyls\python_ls.py", line 294, in m_text_document__references
    return self.references(textDocument['uri'], position, exclude_declaration)
  File "d:\python-language-server\pyls\python_ls.py", line 231, in references
    exclude_declaration=exclude_declaration
  File "d:\python-language-server\pyls\python_ls.py", line 127, in _hook
    return hook_handlers(config=self.config, workspace=self.workspace, document=doc, **kwargs)
  File "f:\python\lib\site-packages\pluggy\__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "f:\python\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "f:\python\lib\site-packages\pluggy\__init__.py", line 182, in __call__
    return outcome.get_result()
  File "f:\python\lib\site-packages\pluggy\callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File "f:\python\lib\site-packages\pluggy\callers.py", line 48, in from_call
    result = func()
  File "f:\python\lib\site-packages\pluggy\__init__.py", line 180, in <lambda>
    outcome = _Result.from_call(lambda: self.oldcall(hook, hook_impls, kwargs))
  File "f:\python\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "f:\python\lib\site-packages\pluggy\callers.py", line 201, in _multicall
    return outcome.get_result()
  File "f:\python\lib\site-packages\pluggy\callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File "f:\python\lib\site-packages\pluggy\callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "d:\python-language-server\pyls\plugins\references.py", line 23, in pyls_references
    } for d in usages]
  File "d:\python-language-server\pyls\plugins\references.py", line 23, in <listcomp>
    } for d in usages]
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```

Related:
1. https://github.com/palantir/python-language-server/issues/362 failed to find highlights of `sys` module
1. https://github.com/palantir/python-language-server/issues/318 Pyflakes linter can throw when offset in syntaxError is None

I just did this to throw this error:
![fsg](https://user-images.githubusercontent.com/5332158/50057355-6a10ad00-0150-11e9-9e72-1467cf4971b4.gif)

```python
File: Data/Packages/MarkdownPreview/markdown_preview.py
122: def load_resource(name):
123:     """Return file contents for files within the package root folder."""
124:     try:
125:         return sublime.load_resource('Packages/{}/{}'.format(__package__, name))
126:     except Exception:
127:         log("Error while load_resource('%s')" % name)
128:         traceback.print_exc()
129:         return ''
```

**Comment by gatesn** [comment]
Are you still able to reproduce this?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
