### ISSUE TITLE
TypeError: goto_assignments() got an unexpected keyword argument 'follow_builtin_imports'

### ISSUE THREAD

**Issue by pplatek** [palantir/python-language-server#469]
With version 0.21.4, the error in the title started appearing, downgrade to 0.21.3 fixes it.
Here is the full stack trace:

2019-01-03 15:55:13,882 UTC - INFO - pyls.python_ls - Server capabilities: {'codeActionProvider': True, 'codeLensProvider': {'resolveProvider': False}, 'completionProvider': {'resolveProvider': False, 'triggerCharacters': ['.']}, 'documen
tFormattingProvider': True, 'documentHighlightProvider': True, 'documentRangeFormattingProvider': True, 'documentSymbolProvider': True, 'definitionProvider': True, 'executeCommandProvider': {'commands': []}, 'hoverProvider': True, 'refere
ncesProvider': True, 'renameProvider': True, 'signatureHelpProvider': {'triggerCharacters': ['(', ',']}, 'textDocumentSync': 2, 'experimental': {}}
2019-01-03 15:55:21,313 UTC - ERROR - jsonrpc.endpoint - Failed to handle request 30
Traceback (most recent call last):
  File "/home/peterp/.local/lib/python3.7/site-packages/jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/home/peterp/.local/lib/python3.7/site-packages/jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "/home/peterp/.local/lib/python3.7/site-packages/jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/home/peterp/.local/lib/python3.7/site-packages/pyls/python_ls.py", line 261, in m_text_document__definition
    return self.definitions(textDocument['uri'], position)
  File "/home/peterp/.local/lib/python3.7/site-packages/pyls/python_ls.py", line 193, in definitions
    return flatten(self._hook('pyls_definitions', doc_uri, position=position))
  File "/home/peterp/.local/lib/python3.7/site-packages/pyls/python_ls.py", line 118, in _hook
    return hook_handlers(config=self.config, workspace=self.workspace, document=doc, **kwargs)
  File "/home/peterp/.local/lib/python3.7/site-packages/pluggy/hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/peterp/.local/lib/python3.7/site-packages/pluggy/manager.py", line 67, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/peterp/.local/lib/python3.7/site-packages/pluggy/_tracing.py", line 80, in __call__
    return outcome.get_result()
  File "/home/peterp/.local/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/peterp/.local/lib/python3.7/site-packages/pluggy/callers.py", line 52, in from_call
    result = func()
  File "/home/peterp/.local/lib/python3.7/site-packages/pluggy/_tracing.py", line 78, in <lambda>
    outcome = _Result.from_call(lambda: self.oldcall(hook, hook_impls, kwargs))
  File "/home/peterp/.local/lib/python3.7/site-packages/pluggy/manager.py", line 61, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/peterp/.local/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/peterp/.local/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/peterp/.local/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/peterp/.local/lib/python3.7/site-packages/pyls/plugins/definition.py", line 13, in pyls_definitions
    follow_builtin_imports=settings.get('follow_builtin_imports', False))
TypeError: goto_assignments() got an unexpected keyword argument 'follow_builtin_imports'

**Comment by gatesn** [comment]
I think we need to bump the Jedi dependency to 0.13.2

**Comment by mleue** [comment]
same error for me

downgrading to 0.21.3 as suggested by @pplatek fixes it for now (thanks for that)
