### ISSUE TITLE
TypeError: an integer is required

### ISSUE THREAD

**Issue by andrewzigerelli** [palantir/python-language-server#624]
Cannot start pyls.

I installed via pip with --user.
```
[andrew ~]$ pyls
Traceback (most recent call last):

  File "/home/andrew/.local/bin/pyls", line 11, in <module>
    sys.exit(main())
  File "/home/andrew/.local/lib/python2.7/site-packages/pyls/__main__.py", line 61, in main
    start_io_lang_server(stdin, stdout, args.check_parent_process, PythonLanguageServer)
  File "/home/andrew/.local/lib/python2.7/site-packages/pyls/python_ls.py", line 65, in start_io_lang_server
    server.start()
  File "/home/andrew/.local/lib/python2.7/site-packages/pyls/python_ls.py", line 88, in start
    self._jsonrpc_stream_reader.listen(self._endpoint.consume)
  File "/home/andrew/.local/lib/python2.7/site-packages/pyls_jsonrpc/streams.py", line 24, in listen
    request_str = self._read_message()
  File "/home/andrew/.local/lib/python2.7/site-packages/pyls_jsonrpc/streams.py", line 56, in _read_message
    return self._rfile.read(content_length)
TypeError: an integer is required
```

However, inside an interpreter, import pyls works.

**Comment by youben11** [comment]
Looks like the call [here](https://github.com/palantir/python-jsonrpc-server/blob/develop/pyls_jsonrpc/streams.py#L46) is returning None, however, it's not normal to have that function call without something sent to stdin, @andrewzigerelli is there anything that may be sending random data to the server by any mean?
