### ISSUE TITLE
ImportError: cannot import name 'IS_WIN' from 'pyls'

### ISSUE THREAD

**Issue by m-d-focke** [palantir/python-language-server#658]
I'm not sure how to fix this problem, any suggestions?

```
C:\Users\user>python -m pyls --help
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\pyls\__main__.py", line 7, in <module>
    from .python_ls import start_io_lang_server, start_tcp_lang_server, PythonLanguageServer
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\pyls\python_ls.py", line 11, in <module>
    from . import lsp, _utils, uris
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\pyls\uris.py", line 8, in <module>
    from pyls import IS_WIN
ImportError: cannot import name 'IS_WIN' from 'pyls' (C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\pyls\__init__.py)
```
Version:
Python 3.7.4
OS:
Windows 10

**Comment by rfirefly** [comment]
use python2

**Comment by borisyelnikoff** [comment]
+1

**Comment by habamax** [comment]
I had the same error with python 3.

The issue was probably that I have installed `pip install pyls` first and then `pip install python-language-server`.

So I have just uninstall `pyls` and `python-language-server` and installed only `python-language-server`.

Now `pyls` runs ok.

**Comment by ccordoba12** [comment]
Ok, thanks for letting us know about it.
