### ISSUE TITLE
python setup.py egg_info" failed with error code 1 

### ISSUE THREAD

**Issue by jwwjcw** [palantir/python-language-server#707]
(base) C:\Users\xxxxx>pip install --user auquan_toolbox
Collecting auquan_toolbox
  Using cached https://files.pythonhosted.org/packages/64/ce/f1f7f1a53b4c9a1c93fccb430c5ac98b6aebeb8ec85d90262e977bed0c96/auquan_toolbox-2.1.91.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\xxxxx\AppData\Local\Temp\pip-install-jdoi2gb3\auquan-toolbox\setup.py", line 2, in <module>
        from backtester.version import __version__
      File "C:\Users\xxxxx\AppData\Local\Temp\pip-install-jdoi2gb3\auquan-toolbox\backtester\__init__.py", line 14, in <module>
        from backtester.plotter import *
      File "C:\Users\xxxxx\AppData\Local\Temp\pip-install-jdoi2gb3\auquan-toolbox\backtester\plotter.py", line 3, in <module>
        import plotly
    ModuleNotFoundError: No module named 'plotly'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\xxxxx\AppData\Local\Temp\pip-install-jdoi2gb3\auquan-toolbox\

**Comment by ccordoba12** [comment]
Your error has nothing to do with this package.

**Comment by jwwjcw** [comment]
So do I get a clue?
