### ISSUE TITLE
Non existent version of pyls required for python-language-server

### ISSUE THREAD

**Issue by mchassy** [palantir/python-language-server#746]
I am trying to install the `ide-python` module for atom which requires `python-language-server`. I installed `python-language-server`, but then I get message which say that I need pyls v 0.19.

![pyls version 0 19 needed](https://user-images.githubusercontent.com/15926092/74940331-287d3100-53e9-11ea-97b5-386ac31c0c1f.png)

But as you can see below, both for python2 and python3 I am at the most recent version of pyls which is 0.1.6. And in any case the version which is installed does not seem to be working correctly.

```
❯ which python
/usr/bin/python
❯ ls -al /usr/bin/python
lrwxrwxrwx 1 root root 7 Oct 10 12:32 /usr/bin/python -> python2
❯ which python3
/usr/bin/python3
❯ ls -al /usr/bin/python3
lrwxrwxrwx 1 root root 9 Oct  2 13:31 /usr/bin/python3 -> python3.7
❯ python -m pyls --help
/usr/bin/python: No module named pyls
❯ python3 -m pyls --help
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/markchassy/.local/lib/python3.7/site-packages/pyls/__main__.py", line 12, in <module>
    from .python_ls import (PythonLanguageServer, start_io_lang_server,
  File "/home/markchassy/.local/lib/python3.7/site-packages/pyls/python_ls.py", line 12, in <module>
    from . import lsp, _utils, uris
  File "/home/markchassy/.local/lib/python3.7/site-packages/pyls/uris.py", line 8, in <module>
    from pyls import IS_WIN
ImportError: cannot import name 'IS_WIN' from 'pyls' (/home/markchassy/.local/lib/python3.7/site-packages/pyls/__init__.py)
❯ pip list installed | grep pyls
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
pyls                     0.1.6          
❯ pip3 list installed | grep pyls
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
pyls                     0.1.6          

~
❯ 




```

**Comment by ccordoba12** [comment]
The message says it all: you need to install the `python-language-server` package, but you installed instead the `pyls` package, which is a different one.

**Comment by f-hipolito** [comment]
@mchassy, and to whoever faces this issue. It can be solved by following the instructions found in this [reply to issue #658](https://github.com/palantir/python-language-server/issues/658#issuecomment-538267726).
