### ISSUE TITLE
"Set changed size durng iteration" traceback in console when loading preferences

### ISSUE THREAD

**Issue by reversefold** [palantir/python-language-server#759]
```
Traceback (most recent call last):
  File "C:\Users\paper\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/core/rpc.py", line 203, in receive_payload
    self.response_handler(payload)
  File "C:\Users\paper\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/core/rpc.py", line 224, in response_handler
    handler(result)
  File "C:\Users\paper\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/core/sessions.py", line 273, in _handle_initialize_result
    self._on_post_initialize(self, None)
  File "C:\Users\paper\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/core/windows.py", line 580, in _handle_post_initialize
    self.documents.add_session(session)
  File "C:\Users\paper\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/core/windows.py", line 117, in add_session
    self._notify_open_documents(session)
  File "C:\Users\paper\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/core/windows.py", line 151, in _notify_open_documents
    for file_name in self._document_states:
RuntimeError: Set changed size during iteration
```

**Comment by reversefold** [comment]
Sorry, wrong project
