### ISSUE TITLE
Formatting hanging indents raises ValueError

### ISSUE THREAD

**Issue by afflux** [palantir/python-language-server#771]
Example file:

```python
def foo():
    print('asdf',
    file=None
    )
```

Formatting this raises:
```
Traceback (most recent call last):
  File "/home/kb/apps/pls-venv/lib/python3.7/site-packages/pyls_jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/home/kb/apps/pls-venv/lib/python3.7/site-packages/pyls_jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "/home/kb/apps/pls-venv/lib/python3.7/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/home/kb/apps/pls-venv/lib/python3.7/site-packages/pyls/python_ls.py", line 347, in m_text_document__range_formatting
    return self.format_range(textDocument['uri'], range)
  File "/home/kb/apps/pls-venv/lib/python3.7/site-packages/pyls/python_ls.py", line 258, in format_range
    return self._hook('pyls_format_range', doc_uri, range=range)
  File "/home/kb/apps/pls-venv/lib/python3.7/site-packages/pyls/python_ls.py", line 155, in _hook
    return hook_handlers(config=self.config, workspace=workspace, document=doc, **kwargs)
  File "/home/kb/apps/pls-venv/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/kb/apps/pls-venv/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/kb/apps/pls-venv/lib/python3.7/site-packages/pluggy/manager.py", line 337, in traced_hookexec
    return outcome.get_result()
  File "/home/kb/apps/pls-venv/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/kb/apps/pls-venv/lib/python3.7/site-packages/pluggy/callers.py", line 52, in from_call
    result = func()
  File "/home/kb/apps/pls-venv/lib/python3.7/site-packages/pluggy/manager.py", line 335, in <lambda>
    outcome = _Result.from_call(lambda: oldcall(hook, hook_impls, kwargs))
  File "/home/kb/apps/pls-venv/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/kb/apps/pls-venv/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/kb/apps/pls-venv/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/kb/apps/pls-venv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/kb/apps/pls-venv/lib/python3.7/site-packages/pyls/plugins/autopep8_format.py", line 26, in pyls_format_range
    return _format(config, document, line_range=line_range)
  File "/home/kb/apps/pls-venv/lib/python3.7/site-packages/pyls/plugins/autopep8_format.py", line 34, in _format
    new_source = fix_code(document.source, options=options)
  File "/home/kb/apps/pls-venv/lib/python3.7/site-packages/autopep8.py", line 3414, in fix_code
    return fix_lines(sio.readlines(), options=options)
  File "/home/kb/apps/pls-venv/lib/python3.7/site-packages/autopep8.py", line 3489, in fix_lines
    fixed_source = fix.fix()
  File "/home/kb/apps/pls-venv/lib/python3.7/site-packages/autopep8.py", line 600, in fix
    aggressive=self.options.aggressive))
  File "/home/kb/apps/pls-venv/lib/python3.7/site-packages/autopep8.py", line 542, in _fix_source
    modified_lines = fix(result)
  File "/home/kb/apps/pls-venv/lib/python3.7/site-packages/autopep8.py", line 616, in _fix_reindent
    num_indent_spaces = int(result['info'].split()[1])
ValueError: invalid literal for int() with base 10: 'continuation'
```

Caused by palantir/python-language-server#719 replacing the autopep8 checker for `pycodestyle.continued_indentation`

**Comment by ccordoba12** [comment]
Please submit a pull request to fix this. Thanks!

**Comment by afflux** [comment]
Not sure how to solve this, really. `autopep8` and `pyls.plugins.pycodestyle_lint` conflict, as they both have to change the globals of `pycodestyle`.
Only way forward I see is deprecating autopep8 support and moving to yapf or black.

**Comment by karolyi** [comment]
Please don't move to black. It's like enforcing something I never voted for as a dev. I like the simplicity of autopep8, and I couldn't configure yapf to make the same formatting changes autopep8 does.

Is there no other way of getting this issue fixed? I'm getting it too.

**Comment by ccordoba12** [comment]
@karolyi, I think you could check that if you're formatting code with autopep8 then that rule should not apply (I don't know exactly how to do it, sorry).

**Comment by pomali** [comment]
This problem occurs even when I have `yapf` installed (yapf should be preferred before autopep8 according to docs).
Uninstalling `autopep8` helps, but it's not ideal solution.

**Comment by lordsutch** [comment]
Here's a solution: temporarily monkey-patch the continued_indentation checker to use autopep8's in `pyls.plugins.autopep8_format._format()` and then monkey-patch it back to use pycodestyle's checker once the format is completed.

Just to help other people who are having a similar problem who are searching via Google to track it down, the following error message can also occur if the end bracket is at the start of the line w/o whitespace (E124):

`ValueError: invalid literal for int() with base 10: 'closing'`
