### ISSUE TITLE
error when do pip install htseq

### ISSUE THREAD

**Issue by citron96** [palantir/python-language-server#785]
Ubuntu
Python 2.7.17
pip 9.0.1

```
Collecting HTSeq
  Downloading https://files.pythonhosted.org/packages/61/7b/7a31e09ced6994d704d696c28b2c85c12d0653ffcfd4a21a3c231e7f58a6/HTSeq-0.12.3.tar.gz (625kB)
    100% |████████████████████████████████| 634kB 1.8MB/s 
    Complete output from command python setup.py egg_info:
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-huAXPs/pysam/
    symlinking folders for python2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-dcbSkC/HTSeq/setup.py", line 256, in <module>
        **kwargs
      File "/home/citronxu/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/home/citronxu/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/citronxu/.local/lib/python2.7/site-packages/setuptools/dist.py", line 721, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/citronxu/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/home/citronxu/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/home/citronxu/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/home/citronxu/.local/lib/python2.7/site-packages/setuptools/dist.py", line 777, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/home/citronxu/.local/lib/python2.7/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['/usr/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp6eO66W', '--quiet', 'pysam']' returned non-zero exit status 1
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-dcbSkC/HTSeq/

```

many thanks in advance!
------------------------------------------------------
by the way, already updated setuptools.

**Comment by citron96** [comment]
solved with `pip install --upgrade pip`
