### ISSUE TITLE
error message when code completing

### ISSUE THREAD

**Issue by eranif** [palantir/python-language-server#790]
While attempting to code completion a really simple code, the LSP returned an error (assertion)

```
{"jsonrpc":"2.0","method":"textDocument/completion","params":{"textDocument":{"uri":"file:///C:/Users/Eran/Desktop/script.py"},"position":{"line":33,"character":6}},"id":33}
[19:29:10:995 DBG] [Main] 2020-04-25 19:29:10,984 UTC - ERROR - pyls_jsonrpc.endpoint - Failed to handle request 33

Traceback (most recent call last):
  File "C:\python38-64\lib\site-packages\jedi\cache.py", line 141, in wrapper
    return dct[key]

KeyError: ((), frozenset())
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\python38-64\lib\site-packages\pyls_jsonrpc\endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "C:\python38-64\lib\site-packages\pyls_jsonrpc\endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "C:\python38-64\lib\site-packages\pyls_jsonrpc\dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "C:\python38-64\lib\site-packages\pyls\python_ls.py", line 321, in m_text_document__completion
    return self.completions(textDocument['uri'], position)
  File "C:\python38-64\lib\site-packages\pyls\python_ls.py", line 239, in completions
    completions = self._hook('pyls_completions', doc_uri, position=position)
  File "C:\python38-64\lib\site-packages\pyls\python_ls.py", line 155, in _hook
    return hook_handlers(config=self.config, workspace=workspace, document=doc, **kwargs)
  File "C:\python38-64\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "C:\python38-64\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\python38-64\lib\site-packages\pluggy\manager.py", line 337, in traced_hookexec
    return outcome.get_result()
  File "C:\python38-64\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\python38-64\lib\site-packages\pluggy\callers.py", line 52, in from_call
    result = func()
  File "C:\python38-64\lib\site-packages\pluggy\manager.py", line 335, in <lambda>
    outcome = _Result.from_call(lambda: oldcall(hook, hook_impls, kwargs))
  File "C:\python38-64\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "C:\python38-64\lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "C:\python38-64\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\python38-64\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "C:\python38-64\lib\site-packages\pyls\plugins\jedi_completion.py", line 54, in pyls_completions
    definitions = document.jedi_script(position).completions()
  File "C:\python38-64\lib\site-packages\jedi\api\__init__.py", line 217, in completions
    return completion.completions(fuzzy)
  File "C:\python38-64\lib\site-packages\jedi\api\completion.py", line 94, in completions
    return self._completions(fuzzy, **kwargs)
  File "C:\python38-64\lib\site-packages\jedi\api\completion.py", line 109, in _completions
    completion_names = self._get_value_completions(leaf)
  File "C:\python38-64\lib\site-packages\jedi\api\completion.py", line 218, in _get_value_completions
    completion_names += self._trailer_completions(dot.get_previous_leaf())
  File "C:\python38-64\lib\site-packages\jedi\api\completion.py", line 270, in _trailer_completions
    completion_names += filter.values()
  File "C:\python38-64\lib\site-packages\jedi\inference\filters.py", line 243, in values
    return [n for filter in self._filters for n in filter.values()]
  File "C:\python38-64\lib\site-packages\jedi\inference\filters.py", line 243, in <listcomp>
    return [n for filter in self._filters for n in filter.values()]
  File "C:\python38-64\lib\site-packages\jedi\inference\filters.py", line 90, in values
    return self._convert_names(
  File "C:\python38-64\lib\site-packages\jedi\inference\filters.py", line 87, in _convert_names
    return [self.name_class(self.parent_context, name) for name in names]
  File "C:\python38-64\lib\site-packages\jedi\inference\filters.py", line 87, in <listcomp>
    return [self.name_class(self.parent_context, name) for name in names]
  File "C:\python38-64\lib\site-packages\jedi\inference\filters.py", line 93, in <genexpr>
    for name in self._filter(
  File "C:\python38-64\lib\site-packages\jedi\inference\filters.py", line 122, in _filter
    return list(self._check_flows(names))
  File "C:\python38-64\lib\site-packages\jedi\inference\filters.py", line 133, in _check_flows
    check = flow_analysis.reachability_check(
  File "C:\python38-64\lib\site-packages\jedi\inference\flow_analysis.py", line 78, in reachability_check
    return _break_check(context, value_scope, first_flow_scope, node)
  File "C:\python38-64\lib\site-packages\jedi\inference\flow_analysis.py", line 93, in _break_check
    reachable = _check_if(context, flow_node)
  File "C:\python38-64\lib\site-packages\jedi\inference\flow_analysis.py", line 113, in _check_if
    types = context.infer_node(node)
  File "C:\python38-64\lib\site-packages\jedi\inference\context.py", line 210, in infer_node
    return infer_node(self, node)
  File "C:\python38-64\lib\site-packages\jedi\inference\syntax_tree.py", line 148, in infer_node
    return _infer_node_if_inferred(context, element)
  File "C:\python38-64\lib\site-packages\jedi\inference\syntax_tree.py", line 161, in _infer_node_if_inferred
    return _infer_node_cached(context, element)
  File "C:\python38-64\lib\site-packages\jedi\inference\cache.py", line 42, in wrapper
    rv = function(obj, *args, **kwargs)
  File "C:\python38-64\lib\site-packages\jedi\inference\syntax_tree.py", line 166, in _infer_node_cached
    return _infer_node(context, element)
  File "C:\python38-64\lib\site-packages\jedi\debug.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "C:\python38-64\lib\site-packages\jedi\inference\syntax_tree.py", line 62, in wrapper
    return func(context, *args, **kwargs)
  File "C:\python38-64\lib\site-packages\jedi\inference\syntax_tree.py", line 248, in _infer_node
    return infer_or_test(context, element)
  File "C:\python38-64\lib\site-packages\jedi\inference\syntax_tree.py", line 453, in infer_or_test
    types = context.infer_node(next(iterator))
  File "C:\python38-64\lib\site-packages\jedi\inference\context.py", line 210, in infer_node
    return infer_node(self, node)
  File "C:\python38-64\lib\site-packages\jedi\inference\syntax_tree.py", line 148, in infer_node
    return _infer_node_if_inferred(context, element)
  File "C:\python38-64\lib\site-packages\jedi\inference\syntax_tree.py", line 161, in _infer_node_if_inferred
    return _infer_node_cached(context, element)
  File "C:\python38-64\lib\site-packages\jedi\inference\cache.py", line 42, in wrapper
    rv = function(obj, *args, **kwargs)
  File "C:\python38-64\lib\site-packages\jedi\inference\syntax_tree.py", line 166, in _infer_node_cached
    return _infer_node(context, element)
  File "C:\python38-64\lib\site-packages\jedi\debug.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "C:\python38-64\lib\site-packages\jedi\inference\syntax_tree.py", line 62, in wrapper
    return func(context, *args, **kwargs)
  File "C:\python38-64\lib\site-packages\jedi\inference\syntax_tree.py", line 248, in _infer_node
    return infer_or_test(context, element)
  File "C:\python38-64\lib\site-packages\jedi\inference\syntax_tree.py", line 470, in infer_or_test
    types = _infer_comparison(context, types, operator,
  File "C:\python38-64\lib\site-packages\jedi\inference\syntax_tree.py", line 522, in _infer_comparison
    return ValueSet.from_sets(
  File "C:\python38-64\lib\site-packages\jedi\common\value.py", line 32, in from_sets
    for set_ in sets:
  File "C:\python38-64\lib\site-packages\jedi\inference\syntax_tree.py", line 523, in <genexpr>
    _infer_comparison_part(state, context, left, operator, right)
  File "C:\python38-64\lib\site-packages\jedi\inference\syntax_tree.py", line 601, in _infer_comparison_part
    if left.is_compiled() and right.is_compiled():
  File "C:\python38-64\lib\site-packages\jedi\inference\base_value.py", line 287, in __getattr__
    return getattr(self._wrapped_value, name)
  File "C:\python38-64\lib\site-packages\jedi\inference\utils.py", line 75, in wrapper
    return func(*args, **kwds)
  File "C:\python38-64\lib\site-packages\jedi\cache.py", line 143, in wrapper
    result = method(self, *args, **kwargs)
  File "C:\python38-64\lib\site-packages\jedi\inference\base_value.py", line 295, in _wrapped_value
    return self._get_wrapped_value()
  File "C:\python38-64\lib\site-packages\jedi\inference\value\iterable.py", line 202, in _get_wrapped_value
    TupleGenericManager(self._get_generics())
  File "C:\python38-64\lib\site-packages\jedi\inference\value\iterable.py", line 194, in _get_generics
    return (self.merge_types_of_iterate().py__class__(),)
  File "C:\python38-64\lib\site-packages\jedi\inference\base_value.py", line 56, in merge_types_of_iterate
    return ValueSet.from_sets(
  File "C:\python38-64\lib\site-packages\jedi\common\value.py", line 32, in from_sets
    for set_ in sets:
  File "C:\python38-64\lib\site-packages\jedi\inference\base_value.py", line 56, in <genexpr>
    return ValueSet.from_sets(
  File "C:\python38-64\lib\site-packages\jedi\inference\value\iterable.py", line 346, in py__iter__
    for addition in check_array_additions(self._defining_context, self):
  File "C:\python38-64\lib\site-packages\jedi\inference\value\dynamic_arrays.py", line 40, in check_array_additions
    return _internal_check_array_additions(context, sequence)
  File "C:\python38-64\lib\site-packages\jedi\inference\cache.py", line 42, in wrapper
    rv = function(obj, *args, **kwargs)
  File "C:\python38-64\lib\site-packages\jedi\debug.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "C:\python38-64\lib\site-packages\jedi\inference\value\dynamic_arrays.py", line 107, in _internal_check_array_additions
    found = infer_call_of_leaf(
  File "C:\python38-64\lib\site-packages\jedi\inference\helpers.py", line 106, in infer_call_of_leaf
    values = context.infer_node(base)
  File "C:\python38-64\lib\site-packages\jedi\inference\context.py", line 210, in infer_node
    return infer_node(self, node)
  File "C:\python38-64\lib\site-packages\jedi\inference\syntax_tree.py", line 148, in infer_node
    return _infer_node_if_inferred(context, element)
  File "C:\python38-64\lib\site-packages\jedi\inference\syntax_tree.py", line 161, in _infer_node_if_inferred
   return _infer_node_cached(context, element)
  File "C:\python38-64\lib\site-packages\jedi\inference\cache.py", line 42, in wrapper
    rv = function(obj, *args, **kwargs)
  File "C:\python38-64\lib\site-packages\jedi\inference\syntax_tree.py", line 166, in _infer_node_cached
    return _infer_node(context, element)
  File "C:\python38-64\lib\site-packages\jedi\debug.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "C:\python38-64\lib\site-packages\jedi\inference\syntax_tree.py", line 62, in wrapper
    return func(context, *args, **kwargs)
  File "C:\python38-64\lib\site-packages\jedi\inference\syntax_tree.py", line 176, in _infer_node
    return infer_atom(context, element)
  File "C:\python38-64\lib\site-packages\jedi\inference\syntax_tree.py", line 301, in infer_atom
    return context.py__getattribute__(atom, position=position)
  File "C:\python38-64\lib\site-packages\jedi\inference\context.py", line 75, in py__getattribute__
    values = ValueSet.from_sets(name.infer() for name in names)
  File "C:\python38-64\lib\site-packages\jedi\common\value.py", line 32, in from_sets
    for set_ in sets:
  File "C:\python38-64\lib\site-packages\jedi\inference\context.py", line 75, in <genexpr>
    values = ValueSet.from_sets(name.infer() for name in names)
  File "C:\python38-64\lib\site-packages\jedi\inference\names.py", line 234, in infer
    return tree_name_to_values(
  File "C:\python38-64\lib\site-packages\jedi\plugins\__init__.py", line 21, in wrapper
    return built_functions[name](*args, **kwargs)
  File "C:\python38-64\lib\site-packages\jedi\plugins\stdlib.py", line 827, in wrapper
    return func(inference_state, context, tree_name)
  File "C:\python38-64\lib\site-packages\jedi\inference\syntax_tree.py", line 744, in tree_name_to_values
    raise ValueError("Should not happen. type: %s" % typ)
ValueError: Should not happen. type: del_stmt
19:29:11:006 DBG] [Main] [python]  Content-Length: 13466
Content-Type: application/vscode-jsonrpc; charset=utf8
{"jsonrpc": "2.0", "id": 33, "error": {"code": -32602, "message": "ValueError: Should not happen. type: del_stmt", "data": {"traceback": ["  File \"C:\\python38-64\\lib\\site-packages\\pyls_jsonrpc\\endpoint.py\", line 113, in consume\n    self._handle_request(message['id'], message['method'], message.get('params'))\n", "  File \"C:\\python38-64\\lib\\site-packages\\pyls_jsonrpc\\endpoint.py\", line 182, in _handle_request\n    handler_result = handler(params)\n", "  File \"C:\\python38-64\\lib\\site-packages\\pyls_jsonrpc\\dispatchers.py\", line 23, in handler\n    return method(**(params or {}))\n", "  File \"C:\\python38-64\\lib\\site-packages\\pyls\\python_ls.py\", line 321, in m_text_document__completion\n    return self.completions(textDocument['uri'], position)\n", "  File \"C:\\python38-64\\lib\\site-packages\\pyls\\python_ls.py\", line 239, in completions\n    completions = self._hook('pyls_completions', doc_uri, position=position)\n", "  File \"C:\\python38-64\\lib\\site-packages\\pyls\\python_ls.py\", line 155, in _hook\n    return hook_handlers(config=self.config, workspace=workspace, document=doc, **kwargs)\n", "  File \"C:\\python38-64\\lib\\site-packages\\pluggy\\hooks.py\", line 286, in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n", "  File \"C:\\python38-64\\lib\\site-packages\\pluggy\\manager.py\", line 93, in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n", "  File \"C:\\python38-64\\lib\\site-packages\\pluggy\\manager.py\", line 337, in traced_hookexec\n    return outcome.get_result()\n", "  File \"C:\\python38-64\\lib\\site-packages\\pluggy\\callers.py\", line 80, in get_result\n    raise ex[1].with_traceback(ex[2])\n", "  File \"C:\\python38-64\\lib\\site-packages\\pluggy\\callers.py\", line 52, in from_call\n    result = func()\n", "  File \"C:\\python38-64\\lib\\site-packages\\pluggy\\manager.py\", line 335, in <lambda>\n    outcome = _Result.from_call(lambda: oldcall(hook, hook_impls, kwargs))\n", "  File \"C:\\python38-64\\lib\\site-packages\\pluggy\\manager.py\", line 84, in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n", "  File \"C:\\python38-64\\lib\\site-packages\\pluggy\\callers.py\", line 208, in _multicall\n    return outcome.get_result()\n", "  File \"C:\\python38-64\\lib\\site-packages\\pluggy\\callers.py\", line 80, in get_result\n    raise ex[1].with_traceback(ex[2])\n", "  File \"C:\\python38-64\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n", "  File \"C:\\python38-64\\lib\\site-packages\\pyls\\plugins\\jedi_completion.py\", line 54, in pyls_completions\n    definitions = document.jedi_script(position).completions()\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\api\\__init__.py\", line 217, in completions\n    return completion.completions(fuzzy)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\api\\completion.py\", line 94, in completions\n    return self._completions(fuzzy, **kwargs)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\api\\completion.py\", line 109, in _completions\n    completion_names = self._get_value_completions(leaf)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\api\\completion.py\", line 218, in _get_value_completions\n    completion_names += self._trailer_completions(dot.get_previous_leaf())\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\api\\completion.py\", line 270, in _trailer_completions\n    completion_names += filter.values()\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\filters.py\", line 243, in values\n    return [n for filter in self._filters for n in filter.values()]\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\filters.py\", line 243, in <listcomp>\n    return [n for filter in self._filters for n in filter.values()]\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\filters.py\", line 90, in values\n    return self._convert_names(\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\filters.py\", line 87, in _convert_names\n    return [self.name_class(self.parent_context, name) for name in names]\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\filters.py\", line 87, in <listcomp>\n    return [self.name_class(self.parent_context, name) for name in names]\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\filters.py\", line 93, in <genexpr>\n    for name in self._filter(\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\filters.py\", line 122, in _filter\n    return list(self._check_flows(names))\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\filters.py\", line 133, in _check_flows\n    check = flow_analysis.reachability_check(\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\flow_analysis.py\", line 78, in reachability_check\n    return _break_check(context, value_scope, first_flow_scope, node)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\flow_analysis.py\", line 93, in _break_check\n    reachable = _check_if(context, flow_node)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\flow_analysis.py\", line 113, in _check_if\n    types = context.infer_node(node)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\context.py\", line 210, in infer_node\n    return infer_node(self, node)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\syntax_tree.py\", line 148, in infer_node\n    return _infer_node_if_inferred(context, element)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\syntax_tree.py\", line 161, in _infer_node_if_inferred\n    return _infer_node_cached(context, element)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\cache.py\", line 42, in wrapper\n    rv = function(obj, *args, **kwargs)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\syntax_tree.py\", line 166, in _infer_node_cached\n    return _infer_node(context, element)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\debug.py\", line 82, in wrapper\n    return func(*args, **kwargs)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\syntax_tree.py\", line 62, in wrapper\n    return func(context, *args, **kwargs)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\syntax_tree.py\", line 248, in _infer_node\n    return infer_or_test(context, element)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\syntax_tree.py\", line 453, in infer_or_test\n    types = context.infer_node(next(iterator))\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\context.py\", line 210, in infer_node\n    return infer_node(self, node)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\syntax_tree.py\", line 148, in infer_node\n    return _infer_node_if_inferred(context, element)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\syntax_tree.py\", line 161, in _infer_node_if_inferred\n    return _infer_node_cached(context, element)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\cache.py\", line 42, in wrapper\n    rv = function(obj, *args, **kwargs)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\syntax_tree.py\", line 166, in _infer_node_cached\n    return _infer_node(context, element)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\debug.py\", line 82, in wrapper\n    return func(*args, **kwargs)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\syntax_tree.py\", line 62, in wrapper\n    return func(context, *args, **kwargs)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\syntax_tree.py\", line 248, in _infer_node\n    return infer_or_test(context, element)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\syntax_tree.py\", line 470, in infer_or_test\n    types = _infer_comparison(context, types, operator,\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\syntax_tree.py\", line 522, in _infer_comparison\n    return ValueSet.from_sets(\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\common\\value.py\", line 32, in from_sets\n    for set_ in sets:\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\syntax_tree.py\", line 523, in <genexpr>\n    _infer_comparison_part(state, context, left, operator, right)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\syntax_tree.py\", line 601, in _infer_comparison_part\n    if left.is_compiled() and right.is_compiled():\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\base_value.py\", line 287, in __getattr__\n    return getattr(self._wrapped_value, name)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\utils.py\", line 75, in wrapper\n    return func(*args, **kwds)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\cache.py\", line 143, in wrapper\n    result = method(self, *args, **kwargs)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\base_value.py\", line 295, in _wrapped_value\n    return self._get_wrapped_value()\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\value\\iterable.py\", line 202, in _get_wrapped_value\n    TupleGenericManager(self._get_generics())\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\value\\iterable.py\", line 194, in _get_generics\n    return (self.merge_types_of_iterate().py__class__(),)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\base_value.py\", line 56, in merge_types_of_iterate\n    return ValueSet.from_sets(\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\common\\value.py\", line 32, in from_sets\n    for set_ in sets:\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\base_value.py\", line 56, in <genexpr>\n    return ValueSet.from_sets(\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\value\\iterable.py\", line 346, in py__iter__\n    for addition in check_array_additions(self._defining_context, self):\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\value\\dynamic_arrays.py\", line 40, in check_array_additions\n    return _internal_check_array_additions(context, sequence)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\cache.py\", line 42, in wrapper\n    rv = function(obj, *args, **kwargs)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\debug.py\", line 82, in wrapper\n    return func(*args, **kwargs)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\value\\dynamic_arrays.py\", line 107, in _internal_check_array_additions\n    found = infer_call_of_leaf(\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\helpers.py\", line 106, in infer_call_of_leaf\n    values = context.infer_node(base)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\context.py\", line 210, in infer_node\n    return infer_node(self, node)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\syntax_tree.py\", line 148, in infer_node\n    return _infer_node_if_inferred(context, element)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\syntax_tree.py\", line 161, in _infer_node_if_inferred\n    return _infer_node_cached(context, element)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\cache.py\", line 42, in wrapper\n    rv = function(obj, *args, **kwargs)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\syntax_tree.py\", line 166, in _infer_node_cached\n    return _infer_node(context, element)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\debug.py\", line 82, in wrapper\n    return func(*args, **kwargs)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\syntax_tree.py\", line 62, in wrapper\n    return func(context, *args, **kwargs)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\syntax_tree.py\", line 176, in _infer_node\n    return infer_atom(context, element)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\syntax_tree.py\", line 301, in infer_atom\n    return context.py__getattribute__(atom, position=position)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\context.py\", line 75, in py__getattribute__\n    values = ValueSet.from_sets(name.infer() for name in names)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\common\\value.py\", line 32, in from_sets\n    for set_ in sets:\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\context.py\", line 75, in <genexpr>\n    values = ValueSet.from_sets(name.infer() for name in names)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\names.py\", line 234, in infer\n    return tree_name_to_values(\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\plugins\\__init__.py\", line 21, in wrapper\n    return built_functions[name](*args, **kwargs)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\plugins\\stdlib.py\", line 827, in wrapper\n    return func(inference_state, context, tree_name)\n", "  File \"C:\\python38-64\\lib\\site-packages\\jedi\\inference\\syntax_tree.py\", line 744, in tree_name_to_values\n    raise ValueError(\"Should not happen. type: %s\" % typ)\n"]}}}
```

Sample code:

```python
import os

def method():
    os. # <-- this triggers the error
```

Testes on Windows 10, 64 bit. Python 3.8 
```bash
C:\python38-64\Scripts>pip list
Package                Version
---------------------- -------
astroid                2.3.3
autopep8               1.5.2
colorama               0.4.3
entrypoints            0.3
flake8                 3.7.9
isort                  4.3.21
jedi                   0.15.2
lazy-object-proxy      1.4.3
mccabe                 0.6.1
parso                  0.7.0
pip                    20.0.2
pluggy                 0.13.1
python-jsonrpc-server  0.3.4
python-language-server 0.31.10
rope                   0.16.0
setuptools             46.1.3
six                    1.14.0
snowballstemmer        2.0.0
wheel                  0.34.2
wrapt                  1.11.2
yapf                   0.29.0
```

Note that other code methods / libraries are mostly completing without an issue

```

**Comment by ccordoba12** [comment]
> parso                  0.7.0

Your parso version is incorrect. For Jedi 0.15.2 you need to parso 0.5.2.

**Comment by eranif** [comment]
thanks for pointing this out. I am pretty newbie to python (and pip in general).
So should I **downgrade** my parso to `0.5.2` (It seems that I currently have parso `0.7.0`)?

**Comment by eranif** [comment]
update: thanks for the quick suggestion. I forced parso to `0.5.2` and now it works as expected:

I used `pip install parso==0.5.2 --force-reinstall`

and now it code complete the above sample as expected. Thanks!

<img width="991" alt="python-cc-working" src="https://user-images.githubusercontent.com/3677711/80285802-0927ba80-8730-11ea-8c53-1bea178b63a8.png">

**Comment by ccordoba12** [comment]
No prob :+1:
