### ISSUE TITLE
KeyError: 'arguments'  and no completion

### ISSUE THREAD

**Issue by halloleo** [palantir/python-language-server#810]
I'm using pyls (installed from pypi) with [emacs-lsp](https://github.com/emacs-lsp/lsp-mode) and got it sort of working, but on completion I get sometimes the error

KeyError: 'arguments' 

and no completion. Any idea how to fix this?

<details>
  <summary>Full Python Traceback (click to expand)</summary>

```
Traceback (most recent call last):
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/cache.py", line 141, in wrapper
    return dct[key]
KeyError: ((), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/pyls_jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/pyls_jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/pyls_jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/pyls/python_ls.py", line 321, in m_text_document__completion
    return self.completions(textDocument['uri'], position)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/pyls/python_ls.py", line 239, in completions
    completions = self._hook('pyls_completions', doc_uri, position=position)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/pyls/python_ls.py", line 155, in _hook
    return hook_handlers(config=self.config, workspace=workspace, document=doc, **kwargs)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/pluggy/manager.py", line 337, in traced_hookexec
    return outcome.get_result()
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/pluggy/callers.py", line 52, in from_call
    result = func()
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/pluggy/manager.py", line 335, in <lambda>
    outcome = _Result.from_call(lambda: oldcall(hook, hook_impls, kwargs))
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/pyls/plugins/jedi_completion.py", line 72, in pyls_completions
    return [_format_completion(d, include_params) for d in definitions] or None
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/pyls/plugins/jedi_completion.py", line 72, in <listcomp>
    return [_format_completion(d, include_params) for d in definitions] or None
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/pyls/plugins/jedi_completion.py", line 127, in _format_completion
    'label': _label(d),
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/pyls/plugins/jedi_completion.py", line 166, in _label
    if definition.type in ('function', 'method') and hasattr(definition, 'params'):
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/cache.py", line 143, in wrapper
    result = method(self, *args, **kwargs)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/api/classes.py", line 344, in params
    for value in self._name.infer():
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/inference/base_value.py", line 413, in wrapper
    return ValueSet(func(*args, **kwargs))
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/common/value.py", line 16, in __init__
    self._set = frozenset(iterable)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/inference/value/instance.py", line 487, in infer
    for result_value in self._class_member_name.infer():
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/inference/base_value.py", line 413, in wrapper
    return ValueSet(func(*args, **kwargs))
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/common/value.py", line 16, in __init__
    self._set = frozenset(iterable)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/inference/value/klass.py", line 68, in infer
    self.parent_context.inference_state, self.parent_context, self.tree_name)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/plugins/__init__.py", line 21, in wrapper
    return built_functions[name](*args, **kwargs)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/plugins/stdlib.py", line 827, in wrapper
    return func(inference_state, context, tree_name)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 734, in tree_name_to_values
    types = _apply_decorators(context, node)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/inference/cache.py", line 42, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 785, in _apply_decorators
    values = dec_values.execute(arguments.ValuesArguments([values]))
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/inference/base_value.py", line 376, in execute
    return ValueSet.from_sets(c.inference_state.execute(c, arguments) for c in self._set)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/common/value.py", line 32, in from_sets
    for set_ in sets:
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/inference/base_value.py", line 376, in <genexpr>
    return ValueSet.from_sets(c.inference_state.execute(c, arguments) for c in self._set)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/plugins/__init__.py", line 21, in wrapper
    return built_functions[name](*args, **kwargs)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/plugins/stdlib.py", line 134, in wrapper
    return call()
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/plugins/stdlib.py", line 109, in call
    return callback(value, arguments=arguments)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/inference/__init__.py", line 119, in execute
    value_set = value.py__call__(arguments=arguments)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/inference/value/function.py", line 88, in py__call__
    return function_execution.infer()
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/inference/value/function.py", line 318, in infer
    return self.get_return_values()
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/inference/cache.py", line 42, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/inference/recursion.py", line 87, in wrapper
    result = func(self, **kwargs)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/inference/value/function.py", line 204, in get_return_values
    value_set |= self.infer_node(children[1])
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/inference/context.py", line 210, in infer_node
    return infer_node(self, node)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 148, in infer_node
    return _infer_node_if_inferred(context, element)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 161, in _infer_node_if_inferred
    return _infer_node_cached(context, element)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/inference/cache.py", line 42, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 166, in _infer_node_cached
    return _infer_node(context, element)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/debug.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 62, in wrapper
    return func(context, *args, **kwargs)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 176, in _infer_node
    return infer_atom(context, element)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 301, in infer_atom
    return context.py__getattribute__(atom, position=position)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/inference/context.py", line 75, in py__getattribute__
    values = ValueSet.from_sets(name.infer() for name in names)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/common/value.py", line 32, in from_sets
    for set_ in sets:
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/inference/context.py", line 75, in <genexpr>
    values = ValueSet.from_sets(name.infer() for name in names)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/inference/names.py", line 237, in infer
    self.tree_name
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/plugins/__init__.py", line 21, in wrapper
    return built_functions[name](*args, **kwargs)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/plugins/stdlib.py", line 827, in wrapper
    return func(inference_state, context, tree_name)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 734, in tree_name_to_values
    types = _apply_decorators(context, node)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/inference/cache.py", line 42, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/inference/syntax_tree.py", line 785, in _apply_decorators
    values = dec_values.execute(arguments.ValuesArguments([values]))
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/inference/base_value.py", line 376, in execute
    return ValueSet.from_sets(c.inference_state.execute(c, arguments) for c in self._set)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/common/value.py", line 32, in from_sets
    for set_ in sets:
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/inference/base_value.py", line 376, in <genexpr>
    return ValueSet.from_sets(c.inference_state.execute(c, arguments) for c in self._set)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/plugins/__init__.py", line 21, in wrapper
    return built_functions[name](*args, **kwargs)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/plugins/stdlib.py", line 133, in wrapper
    return func(value, arguments=arguments, callback=call)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/plugins/stdlib.py", line 548, in functools_partial
    for instance in value.py__call__(arguments)
  File "/home/halloleo/pyls/.venv/lib/python3.7/site-packages/jedi/inference/arguments.py", line 56, in wrapper
    arguments = kwargs.pop('arguments')
KeyError: 'arguments'
```

</details>

**Comment by goanpeca** [comment]
Hi @halloleo, thanks for report.

It seems to be a bug with Jedi, a dependency of the PyLS in charge of providing completions.

It seems to be fixed already
https://github.com/davidhalter/jedi/issues/1574

But we will have to wait for a new version to be released.

Cheers!

**Comment by halloleo** [comment]
Thanks @goanpeca. 

Can I somehow install the new version of Jedi from github into pyls? (I have pyls in its own virtual env).

**Comment by goanpeca** [comment]
@halloleo maybe you could try something like:

`pip install git+git://github.com/davidhalter/jedi.git#egg=jedi` ?

Cheers!
