### ISSUE TITLE
exception with jedi 0.17.1 and 0.17.2

### ISSUE THREAD

**Issue by haraldschilly** [palantir/python-language-server#835]
version: 0.34.1

stacktrace:

```
Traceback (most recent call last):                                                                                                     
  File "/usr/local/bin/pyls", line 5, in <module>                                                                                      
    from pyls.__main__ import main                                                                                                     
  File "/usr/local/lib/python3.8/dist-packages/pyls/__main__.py", line 12, in <module>                                                 
    from .python_ls import (PythonLanguageServer, start_io_lang_server,                                                                
  File "/usr/local/lib/python3.8/dist-packages/pyls/python_ls.py", line 12, in <module>                                                
    from . import lsp, _utils, uris                                                                                                    
  File "/usr/local/lib/python3.8/dist-packages/pyls/_utils.py", line 9, in <module>                                                    
    import jedi                                                                                                                        
  File "/usr/local/lib/python3.8/dist-packages/jedi/__init__.py", line 32, in <module>                                                 
    from jedi.api import Script, Interpreter, set_debug_function, \                                                                    
  File "/usr/local/lib/python3.8/dist-packages/jedi/api/__init__.py", line 24, in <module>                                             
    from jedi.api import classes                                                                                                       
  File "/usr/local/lib/python3.8/dist-packages/jedi/api/classes.py", line 24, in <module>                                              
    from jedi.inference.utils import unite                                                                                             
  File "/usr/local/lib/python3.8/dist-packages/jedi/inference/__init__.py", line 70, in <module>                                       
    from jedi.inference import imports                                                                                                 
  File "/usr/local/lib/python3.8/dist-packages/jedi/inference/imports.py", line 24, in <module>                                        
    from jedi.inference import sys_path                                                                                                
  File "/usr/local/lib/python3.8/dist-packages/jedi/inference/sys_path.py", line 8, in <module>                                        
    from jedi.common import traverse_parents                                                                                           
ImportError: cannot import name 'traverse_parents' from 'jedi.common' (/usr/local/lib/python3.8/dist-packages/jedi/common/__init__.py) 
```

`pip3 install -U jedi==0.17.0` did fix it for me

your requirements seem to be just `jedi<0.18.0,>=0.17.0`

ideally, you fix this to be compatible with jedi 0.17.x :smiley:

**Comment by ccordoba12** [comment]
@haraldschilly, thanks for reporting. However, this us an upstream bug, so please report it here:

https://github.com/davidhalter/jedi
